// Generated by build-dashboard skill — production
// Dispatch Tab: log dispatch (cover + frame), KPIs, charts, stock warning

import { useState, useMemo } from 'react';
import { useData } from './ProductionDashboard';
import { PRODUCT_TYPES, COLORS, ProductColor } from './productCatalog';
import { CodeSelect } from './CodeSelect';

// ─── HELPERS ──────────────────────────────────────────────────────────────────
function fmt(n: number) { return n.toLocaleString(); }
function fmtKg(n: number) { return n >= 1000 ? `${(n / 1000).toFixed(2)} T` : `${n.toFixed(1)} kg`; }
function today() { return new Date().toISOString().slice(0, 10); }
function last14() {
  const d = new Date(); const out: string[] = [];
  for (let i = 13; i >= 0; i--) { const dd = new Date(d); dd.setDate(d.getDate() - i); out.push(dd.toISOString().slice(0, 10)); }
  return out;
}
function monthKey(d: string) { return d.slice(0, 7); }
function lastNMonths(n: number) {
  const now = new Date(); const out: string[] = [];
  for (let i = n - 1; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    out.push(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`);
  }
  return out;
}

const S = {
  card: 'bg-[#1a1f2e] border border-[#2a2f3e] rounded-lg p-4',
  label: 'text-xs text-gray-400 font-mono uppercase tracking-wide mb-1',
  val: 'text-2xl font-bold font-mono text-white',
  sub: 'text-xs text-gray-500 mt-0.5',
  btn: 'px-3 py-1.5 rounded-md text-sm font-medium transition-colors',
  btnPrimary: 'bg-amber-500 text-black hover:bg-amber-400',
  btnGhost: 'bg-[#2a2f3e] text-gray-300 hover:bg-[#363d52]',
  input: 'w-full bg-[#0f1117] border border-[#2a2f3e] rounded px-3 py-1.5 text-sm text-white placeholder-gray-600 focus:outline-none focus:border-amber-500',
  th: 'text-left text-xs text-gray-400 font-mono uppercase px-3 py-2 border-b border-[#2a2f3e]',
  td: 'px-3 py-2 text-sm',
  warn: 'bg-amber-900/40 border border-amber-700 rounded px-3 py-2 text-amber-300 text-sm',
};

// ─── PERIOD FILTER ─────────────────────────────────────────────────────────────
function PeriodFilter() {
  const { dispFilter, setDispFilter } = useData();
  return (
    <div className="flex items-center gap-2 flex-wrap">
      {(['today', '7d', 'month'] as const).map(p => (
        <button key={p} onClick={() => setDispFilter(f => ({ ...f, period: p }))}
          className={`${S.btn} text-xs ${dispFilter.period === p ? S.btnPrimary : S.btnGhost}`}>
          {p === 'today' ? 'Today' : p === '7d' ? '7 Days' : 'This Month'}
        </button>
      ))}
      <div className="flex items-center gap-1 ml-2">
        <input type="date" className={`${S.input} w-36 text-xs`} value={dispFilter.from}
          onChange={e => setDispFilter(f => ({ ...f, period: 'custom', from: e.target.value }))} />
        <span className="text-gray-500 text-xs">–</span>
        <input type="date" className={`${S.input} w-36 text-xs`} value={dispFilter.to}
          onChange={e => setDispFilter(f => ({ ...f, period: 'custom', to: e.target.value }))} />
      </div>
    </div>
  );
}

// ─── DISPATCH FORM ─────────────────────────────────────────────────────────────
interface FormState {
  date: string; code: string; color: ProductColor; cover: string; frame: string; sets: string;
  orderNo: string; salesRef: string; client: string;
  orderDate: string; targetDate: string; chalanNo: string; actualDate: string; vehicleNumber: string;
}
const EMPTY: FormState = {
  date: today(), code: '', color: 'GREY', cover: '', frame: '', sets: '',
  orderNo: '', salesRef: '', client: '', orderDate: '', targetDate: '', chalanNo: '', actualDate: '', vehicleNumber: '',
};

function DispatchForm({ editId, onDone }: { editId?: string; onDone?: () => void }) {
  const { dispatchData, stockPositions, addDispatch, updateDispatch, importDispatchCSV } = useData();
  const [form, setForm] = useState<FormState>(() => {
    if (editId) {
      const e = dispatchData.find(d => d.id === editId);
      if (e) return {
        date: e.date, code: e.code, color: e.color as ProductColor,
        cover: String(e.coverDispatched), frame: String(e.frameDispatched), sets: String(e.setDispatched),
        orderNo: e.orderNo, salesRef: e.salesRef, client: e.client,
        orderDate: e.orderDate, targetDate: e.targetDate, chalanNo: e.chalanNo,
        actualDate: e.actualDate, vehicleNumber: e.vehicleNumber,
      };
    }
    return EMPTY;
  });
  const [saved, setSaved] = useState(false);
  const [importResult, setImportResult] = useState<string | null>(null);

  const stock = useMemo(() => {
    if (!form.code) return null;
    return stockPositions.find(s => s.code === form.code) ?? null;
  }, [form.code, stockPositions]);

  const coverOver = stock !== null && Number(form.cover) > 0 && Number(form.cover) > stock.stockCover;
  const frameOver = stock !== null && Number(form.frame) > 0 && Number(form.frame) > stock.stockFrame;

  function setField(k: keyof FormState, v: string) {
    setForm(f => {
      const next = { ...f, [k]: v };
      // auto-fill sets from cover/frame unless user has manually changed it
      if (k === 'cover' || k === 'frame') {
        const c = Number(k === 'cover' ? v : f.cover) || 0;
        const fr = Number(k === 'frame' ? v : f.frame) || 0;
        next.sets = String(Math.min(c, fr));
      }
      return next;
    });
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const cd = Number(form.cover); const fd = Number(form.frame);
    const sd = form.sets !== '' ? Number(form.sets) : Math.min(cd, fd);
    const meta = {
      orderNo: form.orderNo, salesRef: form.salesRef, client: form.client,
      orderDate: form.orderDate, targetDate: form.targetDate, chalanNo: form.chalanNo,
      actualDate: form.actualDate, vehicleNumber: form.vehicleNumber,
    };
    if (editId) updateDispatch(editId, form.date, form.code, form.color, cd, fd, sd, meta);
    else addDispatch(form.date, form.code, form.color, cd, fd, sd, meta);
    setForm(EMPTY); setSaved(true); setTimeout(() => setSaved(false), 2000);
    onDone?.();
  }

  function handleCSV(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]; if (!file) return;
    const reader = new FileReader();
    reader.onload = ev => {
      const r = importDispatchCSV(ev.target?.result as string);
      setImportResult(`Imported ${r.imported} rows${r.skipped.length ? `, skipped ${r.skipped.length}` : ''}`);
      setTimeout(() => setImportResult(null), 4000);
    };
    reader.readAsText(file); e.target.value = '';
  }

  return (
    <div className={S.card}>
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-semibold text-amber-400 font-mono uppercase tracking-wide">
          {editId ? 'Edit Dispatch' : 'Log Dispatch'}
        </h3>
        {!editId && (
          <label className={`${S.btn} ${S.btnGhost} cursor-pointer text-xs`}>
            Import CSV <input type="file" accept=".csv" className="hidden" onChange={handleCSV} />
          </label>
        )}
      </div>
      {importResult && <div className="mb-3 text-xs text-green-400 font-mono bg-green-900/20 rounded px-2 py-1">{importResult}</div>}
      {(coverOver || frameOver) && (
        <div className={`${S.warn} mb-3`}>
          Warning: dispatching more than available stock
          {coverOver ? ` (cover: ${form.cover} > ${stock?.stockCover ?? 0} in stock)` : ''}
          {frameOver ? ` (frame: ${form.frame} > ${stock?.stockFrame ?? 0} in stock)` : ''}.
          Entry saved — creates backlog.
        </div>
      )}
      <form onSubmit={handleSubmit} className="space-y-3">
        {/* Row 1: product fields */}
        <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
          <div>
            <label className={S.label}>Date</label>
            <input type="date" className={S.input} value={form.date} onChange={e => setField('date', e.target.value)} required />
          </div>
          <div>
            <label className={S.label}>Product Code</label>
            <CodeSelect value={form.code} onChange={v => setField('code', v)} className={S.input} />
          </div>
          <div>
            <label className={S.label}>Color</label>
            <select className={S.input} value={form.color} onChange={e => setField('color', e.target.value as ProductColor)}>
              {COLORS.map(c => <option key={c} value={c}>{c}</option>)}
            </select>
          </div>
          {stock && (
            <div className="flex flex-col justify-end">
              <div className="text-xs font-mono text-gray-400 bg-[#0f1117] rounded px-2 py-1.5 border border-[#2a2f3e]">
                Stock — Cover: <span style={{ color: stock.stockCover < 0 ? '#f87171' : '#4ade80' }}>{stock.stockCover}</span>
                {' '} Frame: <span style={{ color: stock.stockFrame < 0 ? '#f87171' : '#4ade80' }}>{stock.stockFrame}</span>
              </div>
            </div>
          )}
          <div>
            <label className={S.label}>Covers Dispatched</label>
            <input type="number" min="0" className={`${S.input} ${coverOver ? 'border-amber-500' : ''}`}
              value={form.cover} onChange={e => setField('cover', e.target.value)}
              required={!form.sets} />
          </div>
          <div>
            <label className={S.label}>Frames Dispatched</label>
            <input type="number" min="0" className={`${S.input} ${frameOver ? 'border-amber-500' : ''}`}
              value={form.frame} onChange={e => setField('frame', e.target.value)}
              required={!form.sets} />
          </div>
          <div>
            <label className={S.label}>Sets Dispatched</label>
            <input type="number" min="0" className={S.input}
              value={form.sets}
              onChange={e => setForm(f => ({ ...f, sets: e.target.value }))}
              placeholder={String(Math.min(Number(form.cover) || 0, Number(form.frame) || 0))}
            />
          </div>
        </div>
        {/* Row 2: order / logistics fields */}
        <div className="border-t border-[#2a2f3e] pt-3 grid grid-cols-2 gap-3 md:grid-cols-4">
          <div>
            <label className={S.label}>Order No.</label>
            <input type="text" className={S.input} placeholder="e.g. ORD-001" value={form.orderNo} onChange={e => setField('orderNo', e.target.value)} />
          </div>
          <div>
            <label className={S.label}>Sales Ref</label>
            <select className={S.input} value={form.salesRef} onChange={e => setField('salesRef', e.target.value)}>
              <option value="">— Select —</option>
              {['DD','DZ','MTH','JP','LD','MK','MP','RS','RT','TL'].map(r => <option key={r} value={r}>{r}</option>)}
            </select>
          </div>
          <div>
            <label className={S.label}>Client</label>
            <input type="text" className={S.input} placeholder="Client name" value={form.client} onChange={e => setField('client', e.target.value)} />
          </div>
          <div>
            <label className={S.label}>Chalan No.</label>
            <input type="text" className={S.input} placeholder="Challan number" value={form.chalanNo} onChange={e => setField('chalanNo', e.target.value)} />
          </div>
          <div>
            <label className={S.label}>Order Date</label>
            <input type="date" className={S.input} value={form.orderDate} onChange={e => setField('orderDate', e.target.value)} />
          </div>
          <div>
            <label className={S.label}>Target Date</label>
            <input type="date" className={S.input} value={form.targetDate} onChange={e => setField('targetDate', e.target.value)} />
          </div>
          <div>
            <label className={S.label}>Actual Date</label>
            <input type="date" className={S.input} value={form.actualDate} onChange={e => setField('actualDate', e.target.value)} />
          </div>
          <div>
            <label className={S.label}>Vehicle No.</label>
            <input type="text" className={S.input} placeholder="e.g. MH-12-AB-1234" value={form.vehicleNumber} onChange={e => setField('vehicleNumber', e.target.value)} />
          </div>
        </div>
        <div className="flex justify-end gap-2">
          {editId && onDone && <button type="button" onClick={onDone} className={`${S.btn} ${S.btnGhost}`}>Cancel</button>}
          <button type="submit" className={`${S.btn} ${S.btnPrimary}`}>
            {saved ? 'Saved!' : editId ? 'Update' : 'Log Dispatch'}
          </button>
        </div>
      </form>
    </div>
  );
}

// ─── DUAL BAR CHART ────────────────────────────────────────────────────────────
function DualBarChart({ prodByDay, dispByDay }: { prodByDay: Map<string, number>; dispByDay: Map<string, number> }) {
  const days = last14();
  const maxVal = Math.max(...days.map(d => Math.max(prodByDay.get(d) ?? 0, dispByDay.get(d) ?? 0)), 1);
  const H = 100, W = 26;
  return (
    <div className={S.card}>
      <div className={S.label}>14-Day Production vs Dispatch (sets)</div>
      <div className="overflow-x-auto">
        <svg width={days.length * (W * 2 + 10)} height={H + 36}>
          {days.map((d, i) => {
            const prod = prodByDay.get(d) ?? 0; const disp = dispByDay.get(d) ?? 0;
            const x = i * (W * 2 + 10);
            const ph = Math.round((prod / maxVal) * H); const dh = Math.round((disp / maxVal) * H);
            return (
              <g key={d}>
                <rect x={x} y={H - ph} width={W} height={ph} fill="#f59e0b" rx={2} opacity={0.85} />
                {prod > 0 && <text x={x + W / 2} y={H - ph - 3} textAnchor="middle" fill="#f59e0b" fontSize={9}>{prod}</text>}
                <rect x={x + W + 3} y={H - dh} width={W} height={dh} fill="#60a5fa" rx={2} opacity={0.85} />
                {disp > 0 && <text x={x + W + 3 + W / 2} y={H - dh - 3} textAnchor="middle" fill="#60a5fa" fontSize={9}>{disp}</text>}
                <text x={x + W} y={H + 14} textAnchor="middle" fill="#6b7280" fontSize={8}>{d.slice(5)}</text>
              </g>
            );
          })}
          <rect x={0} y={H + 24} width={10} height={8} fill="#f59e0b" rx={1} />
          <text x={14} y={H + 32} fill="#9ca3af" fontSize={9}>Production</text>
          <rect x={72} y={H + 24} width={10} height={8} fill="#60a5fa" rx={1} />
          <text x={86} y={H + 32} fill="#9ca3af" fontSize={9}>Dispatch</text>
        </svg>
      </div>
    </div>
  );
}

// ─── MONTHLY SUMMARY ───────────────────────────────────────────────────────────
function MonthlySummaryTable() {
  const { dispatchData, productionData } = useData();
  const months = lastNMonths(6);
  const rows = months.map(m => {
    const disp = dispatchData.filter(d => monthKey(d.date) === m);
    const prod = productionData.filter(p => monthKey(p.date) === m);
    const dispSets = disp.reduce((a, d) => a + d.setDispatched, 0);
    const prodSets = prod.reduce((a, p) => a + p.setQty, 0);
    const dispWt   = disp.reduce((a, d) => a + d.totalWeightKg, 0);
    return { month: m, prodSets, dispSets, dispWt, gap: prodSets - dispSets };
  });
  return (
    <div className={S.card}>
      <div className={S.label + ' mb-3'}>Monthly Summary (last 6 months)</div>
      <table className="w-full text-sm">
        <thead>
          <tr>{['Month','Produced','Dispatched','Weight','Pending'].map(h => <th key={h} className={S.th}>{h}</th>)}</tr>
        </thead>
        <tbody>
          {rows.map(r => (
            <tr key={r.month} className="border-b border-[#1e2436] hover:bg-[#1e2436]/40">
              <td className={`${S.td} font-mono text-gray-300`}>{r.month}</td>
              <td className={`${S.td} font-mono text-amber-400`}>{fmt(r.prodSets)}</td>
              <td className={`${S.td} font-mono text-blue-400`}>{fmt(r.dispSets)}</td>
              <td className={`${S.td} font-mono text-gray-400`}>{fmtKg(r.dispWt)}</td>
              <td className={`${S.td} font-mono`} style={{ color: r.gap < 0 ? '#f87171' : r.gap > 0 ? '#fbbf24' : '#4ade80' }}>
                {r.gap > 0 ? `+${fmt(r.gap)}` : fmt(r.gap)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// ─── LOG TABLE ─────────────────────────────────────────────────────────────────
function DispatchLogTable() {
  const { dispatchData, deleteDispatch, updateDispatch } = useData();
  const [editId, setEditId] = useState<string | null>(null);

  function handleActualDate(id: string, val: string) {
    const e = dispatchData.find(x => x.id === id);
    if (!e) return;
    updateDispatch(e.id, e.date, e.code, e.color, e.coverDispatched, e.frameDispatched, e.setDispatched, {
      orderNo: e.orderNo, salesRef: e.salesRef, client: e.client,
      orderDate: e.orderDate, targetDate: e.targetDate, chalanNo: e.chalanNo,
      actualDate: val, vehicleNumber: e.vehicleNumber,
    });
  }

  if (editId) return (
    <div>
      <button onClick={() => setEditId(null)} className={`${S.btn} ${S.btnGhost} text-xs mb-3`}>← Back</button>
      <DispatchForm editId={editId} onDone={() => setEditId(null)} />
    </div>
  );

  return (
    <div className={S.card}>
      <div className={S.label + ' mb-3'}>Dispatch Log ({dispatchData.length} entries)</div>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr>{['Order No','Date','Client','Chalan No','Code','Color','Cover','Frame','Sets','Weight','Order Dt','Target Dt','Actual Dt','Status','Vehicle','Sales Ref',''].map(h => <th key={h} className={S.th}>{h}</th>)}</tr>
          </thead>
          <tbody>
            {dispatchData.length === 0 && (
              <tr><td colSpan={17} className="px-3 py-6 text-center text-gray-500">No dispatch entries yet</td></tr>
            )}
            {dispatchData.map(d => (
              <tr key={d.id} className="border-b border-[#1e2436] hover:bg-[#1e2436]/40">
                <td className={`${S.td} font-mono text-amber-400`}>{d.orderNo || '—'}</td>
                <td className={`${S.td} font-mono text-gray-400`}>{d.date}</td>
                <td className={`${S.td} text-gray-300`}>{d.client || '—'}</td>
                <td className={`${S.td} font-mono text-gray-300`}>{d.chalanNo || '—'}</td>
                <td className={`${S.td} font-mono text-white`}>{d.code}</td>
                <td className={`${S.td} text-gray-300`}>{d.color}</td>
                <td className={`${S.td} font-mono text-gray-300`}>{d.coverDispatched}</td>
                <td className={`${S.td} font-mono text-gray-300`}>{d.frameDispatched}</td>
                <td className={`${S.td} font-mono text-blue-400 font-bold`}>{d.setDispatched}</td>
                <td className={`${S.td} font-mono text-gray-400 text-xs`}>{fmtKg(d.totalWeightKg)}</td>
                <td className={`${S.td} font-mono text-gray-500 text-xs`}>{d.orderDate || '—'}</td>
                <td className={`${S.td} font-mono text-gray-500 text-xs`}>{d.targetDate || '—'}</td>
                <td className={S.td}>
                  <input
                    type="date"
                    className="bg-transparent border border-[#2a2f3e] rounded px-1.5 py-0.5 text-xs font-mono text-gray-300 focus:outline-none focus:border-amber-500 w-32"
                    value={d.actualDate}
                    onChange={e => handleActualDate(d.id, e.target.value)}
                  />
                </td>
                <td className={S.td}>
                  {d.dispatchStatus ? (
                    <span className={`text-xs font-medium px-1.5 py-0.5 rounded ${
                      d.dispatchStatus === 'Before Time' ? 'bg-green-900/40 text-green-400' :
                      d.dispatchStatus === 'On Time'    ? 'bg-blue-900/40 text-blue-400' :
                                                          'bg-red-900/40 text-red-400'
                    }`}>{d.dispatchStatus}</span>
                  ) : '—'}
                </td>
                <td className={`${S.td} text-gray-400 text-xs`}>{d.vehicleNumber || '—'}</td>
                <td className={`${S.td} text-gray-500 text-xs`}>{d.salesRef || '—'}</td>
                <td className={S.td}>
                  <div className="flex gap-1">
                    <button onClick={() => setEditId(d.id)} className="text-xs text-amber-400 hover:text-amber-300">Edit</button>
                    <button onClick={() => deleteDispatch(d.id)} className="text-xs text-red-400 hover:text-red-300 ml-1">Del</button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ─── MAIN ──────────────────────────────────────────────────────────────────────
export function DispatchTab() {
  const { filteredDisp, filteredProd, stockPositions } = useData();

  const totalSets    = filteredDisp.reduce((a, d) => a + d.setDispatched, 0);
  const totalWeight  = filteredDisp.reduce((a, d) => a + d.totalWeightKg, 0);
  const prodSets     = filteredProd.reduce((a, p) => a + p.setQty, 0);
  const dispatchGap  = prodSets - totalSets;
  const dispatchRate = prodSets > 0 ? ((totalSets / prodSets) * 100).toFixed(1) : '0.0';
  const backlogCount = stockPositions.filter(s => s.status === 'BACKLOG').length;

  const prodByDay = useMemo(() => {
    const m = new Map<string, number>();
    filteredProd.forEach(p => m.set(p.date, (m.get(p.date) ?? 0) + p.setQty));
    return m;
  }, [filteredProd]);
  const dispByDay = useMemo(() => {
    const m = new Map<string, number>();
    filteredDisp.forEach(d => m.set(d.date, (m.get(d.date) ?? 0) + d.setDispatched));
    return m;
  }, [filteredDisp]);
  const byType = useMemo(() => {
    const m = new Map<string, number>();
    filteredDisp.forEach(d => {
      const pt = PRODUCT_TYPES.find(t => d.code.startsWith(t.prefix));
      const k = pt?.code ?? 'OTHER';
      m.set(k, (m.get(k) ?? 0) + d.setDispatched);
    });
    return Array.from(m.entries()).sort((a, b) => b[1] - a[1]);
  }, [filteredDisp]);
  const maxByType = Math.max(...byType.map(([, v]) => v), 1);

  return (
    <div className="space-y-5">
      <PeriodFilter />
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className={S.card}><div className={S.label}>Sets Dispatched</div><div className={S.val}>{fmt(totalSets)}</div><div className={S.sub}>filtered period</div></div>
        <div className={S.card}><div className={S.label}>Weight Dispatched</div><div className={`${S.val} text-blue-400`}>{fmtKg(totalWeight)}</div></div>
        <div className={S.card}>
          <div className={S.label}>Dispatch Gap</div>
          <div className={`${S.val} ${dispatchGap > 0 ? 'text-amber-400' : 'text-green-400'}`}>{dispatchGap > 0 ? `+${fmt(dispatchGap)}` : fmt(dispatchGap)}</div>
          <div className={S.sub}>produced − dispatched</div>
        </div>
        <div className={S.card}>
          <div className={S.label}>Dispatch Rate</div>
          <div className={`${S.val} text-purple-400`}>{dispatchRate}%</div>
          {backlogCount > 0 && <div className="text-xs text-red-400 mt-1">{backlogCount} SKUs in backlog</div>}
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="md:col-span-2"><DualBarChart prodByDay={prodByDay} dispByDay={dispByDay} /></div>
        <div className={S.card}>
          <div className={S.label + ' mb-3'}>Dispatch by Item Type</div>
          <div className="space-y-2">
            {byType.length === 0 && <div className="text-gray-500 text-sm">No data</div>}
            {byType.map(([type, count]) => {
              const pt = PRODUCT_TYPES.find(t => t.code === type);
              return (
                <div key={type}>
                  <div className="flex justify-between text-xs mb-0.5">
                    <span style={{ color: pt?.color ?? '#9ca3af' }}>{type}</span>
                    <span className="font-mono text-gray-300">{fmt(count)}</span>
                  </div>
                  <div className="h-2 bg-[#2a2f3e] rounded overflow-hidden">
                    <div className="h-full rounded" style={{ width: `${Math.round((count / maxByType) * 100)}%`, background: pt?.color ?? '#9ca3af' }} />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
      <DispatchForm />
      <MonthlySummaryTable />
      <DispatchLogTable />
    </div>
  );
}
