// Generated by build-dashboard skill — production
// Monthly Overview Tab: executive-level summary across all dimensions

import { useMemo } from 'react';
import { useData } from './ProductionDashboard';
import { PRODUCT_TYPES, getCategoryFromCode } from './productCatalog';

function fmt(n: number) { return n.toLocaleString(); }
function fmtKg(n: number) { return n >= 1000 ? `${(n / 1000).toFixed(2)} T` : `${n.toFixed(1)} kg`; }
function monthKey(d: string) { return d.slice(0, 7); }
function lastNMonths(n: number): string[] {
  const now = new Date(); const out: string[] = [];
  for (let i = n - 1; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    out.push(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`);
  }
  return out;
}
function monthLabel(m: string) {
  const [year, month] = m.split('-');
  const names = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  return `${names[Number(month) - 1]} ${year}`;
}

const S = {
  card:  'bg-[#1a1f2e] border border-[#2a2f3e] rounded-lg p-4',
  label: 'text-xs text-gray-400 font-mono uppercase tracking-wide mb-1',
  val:   'text-2xl font-bold font-mono text-white',
  sub:   'text-xs text-gray-500 mt-0.5',
  th:    'text-left text-xs text-gray-400 font-mono uppercase px-3 py-2 border-b border-[#2a2f3e]',
  td:    'px-3 py-2 text-sm',
};

function Trend({ curr, prev }: { curr: number; prev: number }) {
  if (prev === 0) return null;
  const pct = ((curr - prev) / prev) * 100;
  return <span className={`text-xs font-mono ml-1 ${pct >= 0 ? 'text-green-400' : 'text-red-400'}`}>{pct >= 0 ? '↑' : '↓'}{Math.abs(pct).toFixed(1)}%</span>;
}

function Sparkline({ values, color = '#f59e0b' }: { values: number[]; color?: string }) {
  const max = Math.max(...values, 1);
  const W = 80, H = 24, n = values.length;
  if (n < 2) return null;
  const pts = values.map((v, i) => `${(i / (n - 1)) * W},${H - (v / max) * H}`).join(' ');
  return (
    <svg width={W} height={H} style={{ display: 'block' }}>
      <polyline points={pts} fill="none" stroke={color} strokeWidth={1.5} />
      {values.map((v, i) => <circle key={i} cx={(i / (n - 1)) * W} cy={H - (v / max) * H} r={2} fill={color} />)}
    </svg>
  );
}

export function MonthlyOverviewTab() {
  const { productionData, dispatchData, rawMaterialData, stockPositions } = useData();
  const months = lastNMonths(6);

  const monthData = useMemo(() => {
    return months.map(m => {
      const prod = productionData.filter(p => monthKey(p.date) === m);
      const disp = dispatchData.filter(d => monthKey(d.date) === m);
      const rm   = rawMaterialData.filter(r => monthKey(r.date) === m && r.category === 'OUTWARD');

      const prodSets  = prod.reduce((a, p) => a + p.setQty, 0);
      const prodWt    = prod.reduce((a, p) => a + p.totalWeightKg, 0);
      const dispSets  = disp.reduce((a, d) => a + d.setDispatched, 0);
      const rmWeightT = rm.reduce((a, r) => a + r.weightT, 0);

      const byType: Record<string, { prod: number; disp: number }> = {};
      PRODUCT_TYPES.forEach(t => { byType[t.code] = { prod: 0, disp: 0 }; });
      prod.forEach(p => {
        const pt = PRODUCT_TYPES.find(t => p.code.startsWith(t.prefix));
        if (pt) byType[pt.code].prod += p.setQty;
      });
      disp.forEach(d => {
        const pt = PRODUCT_TYPES.find(t => d.code.startsWith(t.prefix));
        if (pt) byType[pt.code].disp += d.setDispatched;
      });

      const commProd = prod.filter(p => getCategoryFromCode(p.code) === 'commercial').reduce((a, p) => a + p.setQty, 0);
      const regProd  = prod.filter(p => getCategoryFromCode(p.code) === 'regular').reduce((a, p) => a + p.setQty, 0);

      return { month: m, prodSets, prodWt, dispSets, rmWeightT, byType, commProd, regProd };
    });
  }, [productionData, dispatchData, rawMaterialData, months]);

  const curr = monthData[monthData.length - 1];
  const prev = monthData[monthData.length - 2];

  const totalStock   = stockPositions.reduce((a, s) => a + Math.max(s.stockSet, 0), 0);
  const backlogCount = stockPositions.filter(s => s.status === 'BACKLOG').length;

  const dispatchRate = curr.prodSets > 0 ? (curr.dispSets / curr.prodSets) * 100 : 0;

  const prodSparkline = monthData.map(m => m.prodSets);
  const dispSparkline = monthData.map(m => m.dispSets);
  const rmSparkline   = monthData.map(m => m.rmWeightT);

  return (
    <div className="space-y-5">
      <div>
        <h2 className="text-lg font-bold text-white font-mono">{monthLabel(curr.month)}</h2>
        <p className="text-xs text-gray-500">Monthly performance overview</p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className={S.card}>
          <div className={S.label}>Sets Produced</div>
          <div className={S.val}>{fmt(curr.prodSets)}</div>
          <div className={S.sub}><Trend curr={curr.prodSets} prev={prev?.prodSets ?? 0} /></div>
          <div className="mt-2"><Sparkline values={prodSparkline} color="#f59e0b" /></div>
        </div>
        <div className={S.card}>
          <div className={S.label}>Dispatch Rate</div>
          <div className={`${S.val} text-purple-400`}>{dispatchRate.toFixed(1)}%</div>
          <div className={S.sub}>of produced sets dispatched</div>
        </div>
        <div className={S.card}>
          <div className={S.label}>Sets Dispatched</div>
          <div className={`${S.val} text-blue-400`}>{fmt(curr.dispSets)}</div>
          <div className={S.sub}><Trend curr={curr.dispSets} prev={prev?.dispSets ?? 0} /></div>
          <div className="mt-2"><Sparkline values={dispSparkline} color="#60a5fa" /></div>
        </div>
        <div className={S.card}>
          <div className={S.label}>RM Consumed</div>
          <div className={`${S.val} text-green-400`}>{curr.rmWeightT.toFixed(2)} T</div>
          <div className={S.sub}><Trend curr={curr.rmWeightT} prev={prev?.rmWeightT ?? 0} /></div>
          <div className="mt-2"><Sparkline values={rmSparkline} color="#4ade80" /></div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className={S.card}>
          <div className={S.label}>Current Stock (sets)</div>
          <div className={`${S.val} text-amber-400`}>{fmt(totalStock)}</div>
          {backlogCount > 0 && <div className="text-xs text-red-400 mt-1">{backlogCount} SKUs in backlog</div>}
        </div>
        <div className={S.card}>
          <div className={S.label}>Commercial Production</div>
          <div className={S.val}>{fmt(curr.commProd)}</div>
          <div className={S.sub}>{curr.prodSets > 0 ? ((curr.commProd / curr.prodSets) * 100).toFixed(1) : 0}% of total</div>
        </div>
        <div className={S.card}>
          <div className={S.label}>Regular Production</div>
          <div className={S.val}>{fmt(curr.regProd)}</div>
          <div className={S.sub}>{curr.prodSets > 0 ? ((curr.regProd / curr.prodSets) * 100).toFixed(1) : 0}% of total</div>
        </div>
      </div>

      <div className={S.card}>
        <div className={S.label + ' mb-3'}>Dispatch Rate</div>
        <div className="flex items-center gap-3">
          <div className="flex-1 h-4 bg-[#2a2f3e] rounded overflow-hidden">
            <div className="h-full rounded bg-blue-500" style={{ width: `${Math.min(dispatchRate, 100)}%` }} />
          </div>
          <span className="font-mono text-sm text-blue-400 w-14 text-right">{dispatchRate.toFixed(1)}%</span>
        </div>
      </div>

      <div className={S.card}>
        <div className={S.label + ' mb-3'}>6-Month Trend</div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr>
                {['Month','Produced','Dispatched','Dispatch%','RM (T)','Prod Wt'].map(h => <th key={h} className={S.th}>{h}</th>)}
              </tr>
            </thead>
            <tbody>
              {monthData.map((m, i) => {
                const dr = m.prodSets > 0 ? (m.dispSets / m.prodSets) * 100 : 0;
                const isCurrent = i === monthData.length - 1;
                return (
                  <tr key={m.month} className={`border-b border-[#1e2436] ${isCurrent ? 'bg-amber-950/20' : 'hover:bg-[#1e2436]/40'}`}>
                    <td className={`${S.td} font-mono text-xs ${isCurrent ? 'text-amber-400 font-bold' : 'text-gray-300'}`}>{monthLabel(m.month)}</td>
                    <td className={`${S.td} font-mono text-white`}>{fmt(m.prodSets)}</td>
                    <td className={`${S.td} font-mono text-blue-400`}>{fmt(m.dispSets)}</td>
                    <td className={`${S.td} font-mono text-xs`} style={{ color: dr >= 70 ? '#4ade80' : dr >= 40 ? '#fbbf24' : '#f87171' }}>{dr.toFixed(1)}%</td>
                    <td className={`${S.td} font-mono text-green-400`}>{m.rmWeightT.toFixed(2)}</td>
                    <td className={`${S.td} font-mono text-gray-400 text-xs`}>{fmtKg(m.prodWt)}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      <div className={S.card}>
        <div className={S.label + ' mb-3'}>Item Type Breakdown — {monthLabel(curr.month)}</div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {PRODUCT_TYPES.map(t => {
            const { prod, disp } = curr.byType[t.code] ?? { prod: 0, disp: 0 };
            if (prod === 0 && disp === 0) return null;
            return (
              <div key={t.code} className="bg-[#0f1117] rounded-lg p-3 border border-[#2a2f3e]">
                <div className="text-xs font-mono mb-1" style={{ color: t.color }}>{t.label}</div>
                <div className="text-lg font-mono font-bold text-white">{fmt(prod)}</div>
                <div className="text-xs text-gray-400 font-mono">→ {fmt(disp)} dispatched</div>
                {prod > 0 && (
                  <div className="mt-1 h-1.5 bg-[#2a2f3e] rounded overflow-hidden">
                    <div className="h-full rounded" style={{ width: `${Math.min((disp / prod) * 100, 100)}%`, background: t.color }} />
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

