// Generated by build-dashboard skill — production
import { useState, useMemo } from 'react';
import { useData } from './ProductionDashboard';
import { getWeights, getCategoryFromCode } from './productCatalog';
import { ProductionEntry, DateFilter, todayISO, formatDate } from './useProductionData';
import { CodeSelect } from './CodeSelect';

// ─── SHARED COMPONENTS ────────────────────────────────────────────────────────

function KpiCard({ label, value, sub, accent }: { label: string; value: string | number; sub?: string; accent?: string }) {
  return (
    <div className="rounded-xl p-4 border border-[#2a2f3e]" style={{ background: '#151824' }}>
      <div className="text-xs text-gray-400 font-mono uppercase tracking-widest mb-1">{label}</div>
      <div className="text-2xl font-bold font-mono" style={{ color: accent ?? '#f59e0b' }}>{value}</div>
      {sub && <div className="text-xs text-gray-500 mt-1">{sub}</div>}
    </div>
  );
}

function PeriodFilter({ filter, onChange }: { filter: DateFilter; onChange: (f: DateFilter) => void }) {
  const periods = [
    { id: 'today' as const, label: 'Today' },
    { id: '7d' as const, label: 'Last 7 Days' },
    { id: 'month' as const, label: 'This Month' },
    { id: 'custom' as const, label: 'Custom' },
  ];
  return (
    <div className="flex items-center gap-2 flex-wrap">
      {periods.map(p => (
        <button key={p.id} onClick={() => onChange({ ...filter, period: p.id })}
          className={`px-3 py-1 rounded text-xs font-mono transition-colors ${
            filter.period === p.id ? 'bg-amber-500 text-black' : 'bg-[#2a2f3e] text-gray-300 hover:bg-[#363d52]'
          }`}>{p.label}</button>
      ))}
      {filter.period === 'custom' && (
        <div className="flex items-center gap-2">
          <input type="date" value={filter.from} onChange={e => onChange({ ...filter, from: e.target.value })}
            className="bg-[#2a2f3e] text-gray-200 text-xs rounded px-2 py-1 border border-[#363d52]" />
          <span className="text-gray-500 text-xs">to</span>
          <input type="date" value={filter.to} onChange={e => onChange({ ...filter, to: e.target.value })}
            className="bg-[#2a2f3e] text-gray-200 text-xs rounded px-2 py-1 border border-[#363d52]" />
        </div>
      )}
    </div>
  );
}

function ImportBanner({ result, onDismiss }: { result: { imported: number; skipped: string[] } | null; onDismiss: () => void }) {
  if (!result) return null;
  return (
    <div className={`flex items-start justify-between p-3 rounded-lg text-sm border ${
      result.skipped.length > 0 ? 'border-amber-600 bg-amber-950 text-amber-200' : 'border-green-700 bg-green-950 text-green-200'
    }`}>
      <div>
        <span className="font-bold">{result.imported} rows imported.</span>
        {result.skipped.length > 0 && (
          <span className="ml-2 text-xs">{result.skipped.length} skipped: {result.skipped.slice(0, 3).join(', ')}</span>
        )}
      </div>
      <button onClick={onDismiss} className="ml-4 opacity-60 hover:opacity-100 text-lg leading-none">&times;</button>
    </div>
  );
}

// ─── SIMPLE SVG BAR CHART ─────────────────────────────────────────────────────
function BarChart({ data, color = '#f59e0b' }:
  { data: { label: string; value: number }[]; color?: string }) {
  const max = Math.max(...data.map(d => d.value), 1);
  const H = 100; const barW = Math.max(8, Math.floor(360 / data.length) - 4);
  return (
    <svg viewBox={`0 0 ${data.length * (barW + 4)} ${H + 24}`} className="w-full" style={{ maxHeight: 140 }}>
      {data.map((d, i) => {
        const h = Math.max(2, (d.value / max) * H);
        return (
          <g key={i}>
            <rect x={i * (barW + 4)} y={H - h} width={barW} height={h} fill={color} opacity={0.85} rx={2} />
            <text x={i * (barW + 4) + barW / 2} y={H + 14} textAnchor="middle"
              fontSize={7} fill="#9ca3af" fontFamily="monospace">
              {d.label.length > 5 ? d.label.substring(0, 5) : d.label}
            </text>
          </g>
        );
      })}
    </svg>
  );
}

// Returns the total sets for a list of entries, pairing extras cumulatively
function groupedSets(entries: ProductionEntry[]): number {
  const g = new Map<string, { cover: number; frame: number }>();
  entries.forEach(e => {
    const k = e.code;
    if (!g.has(k)) g.set(k, { cover: 0, frame: 0 });
    const r = g.get(k)!;
    r.cover += e.coverQty;
    r.frame += e.frameQty;
  });
  let sets = 0;
  g.forEach(r => { sets += Math.min(r.cover, r.frame); });
  return sets;
}

// ─── PENDING ROW TYPE ─────────────────────────────────────────────────────────
interface PendingProdRow {
  localId: string;
  date: string;
  code: string;
  cover: number;
  frame: number;
}

// ─── BATCH ENTRY PANEL ────────────────────────────────────────────────────────
interface BatchProdPanelProps {
  onSubmitAll: (rows: PendingProdRow[]) => Promise<void>;
  onCancel: () => void;
}

function BatchProductionPanel({ onSubmitAll, onCancel }: BatchProdPanelProps) {
  const [date, setDate]     = useState(todayISO());
  const [code, setCode]     = useState('');
  const [cover, setCover]   = useState(0);
  const [frame, setFrame]   = useState(0);
  const [rows, setRows]     = useState<PendingProdRow[]>([]);
  const [submitting, setSubmitting] = useState(false);

  const weights    = code ? getWeights(code) : undefined;
  const setQty     = Math.min(cover, frame);
  const extraCover = cover - setQty;
  const extraFrame = frame - setQty;
  const setWt      = weights ? setQty * weights.setKg : 0;
  const totalWt    = weights ? (cover * weights.coverKg) + (frame * weights.frameKg) : 0;

  function addRow() {
    if (!code || !date) return;
    setRows(prev => [...prev, {
      localId: `${Date.now()}-${Math.random()}`,
      date, code, cover, frame,
    }]);
    // Reset qty fields; keep date sticky
    setCode('');
    setCover(0);
    setFrame(0);
  }

  function removeRow(id: string) {
    setRows(prev => prev.filter(r => r.localId !== id));
  }

  async function handleSubmit() {
    if (rows.length === 0) return;
    setSubmitting(true);
    await onSubmitAll(rows);
    setSubmitting(false);
  }

  return (
    <div className="p-4 rounded-xl border border-[#2a2f3e] mb-4 space-y-4" style={{ background: '#151824' }}>

      {/* ── Row input form ── */}
      <div className="text-xs text-amber-400 font-mono uppercase tracking-widest mb-1">Add a row</div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <div>
          <label className="text-xs text-gray-400 block mb-1">Date</label>
          <input type="date" value={date} onChange={e => setDate(e.target.value)}
            className="w-full bg-[#0f1117] border border-[#2a2f3e] rounded px-2 py-1.5 text-sm text-gray-200" />
        </div>
        <div className="col-span-3">
          <label className="text-xs text-gray-400 block mb-1">Product Code</label>
          <CodeSelect value={code} onChange={setCode}
            className="w-full bg-[#0f1117] border border-[#2a2f3e] rounded px-2 py-1.5 text-sm text-gray-200 font-mono" />
        </div>
      </div>

      {code && weights && (
        <div className="flex gap-4 text-xs font-mono text-gray-400 bg-[#0f1117] rounded px-3 py-2">
          <span>Cover: <span className="text-amber-400">{weights.coverKg} kg</span></span>
          <span>Frame: <span className="text-amber-400">{weights.frameKg} kg</span></span>
          <span>Set: <span className="text-amber-400">{weights.setKg} kg</span></span>
        </div>
      )}

      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <div>
          <label className="text-xs text-gray-400 block mb-1">Cover Qty</label>
          <input type="number" min={0} value={cover} onChange={e => setCover(Number(e.target.value))}
            className="w-full bg-[#0f1117] border border-[#2a2f3e] rounded px-2 py-1.5 text-sm text-gray-200 font-mono" />
        </div>
        <div>
          <label className="text-xs text-gray-400 block mb-1">Frame Qty</label>
          <input type="number" min={0} value={frame} onChange={e => setFrame(Number(e.target.value))}
            className="w-full bg-[#0f1117] border border-[#2a2f3e] rounded px-2 py-1.5 text-sm text-gray-200 font-mono" />
        </div>
        <div>
          <label className="text-xs text-gray-400 block mb-1">Sets <span className="text-gray-600">(auto)</span></label>
          <div className="px-2 py-1.5 rounded bg-[#0a0d12] border border-[#1e2433] text-sm font-mono text-amber-400">{setQty}</div>
        </div>
        <div>
          <label className="text-xs text-gray-400 block mb-1">Extra C / F</label>
          <div className="px-2 py-1.5 rounded bg-[#0a0d12] border border-[#1e2433] text-sm font-mono">
            <span className={extraCover > 0 ? 'text-amber-400' : 'text-gray-500'}>{extraCover}</span>
            <span className="text-gray-600"> / </span>
            <span className={extraFrame > 0 ? 'text-amber-400' : 'text-gray-500'}>{extraFrame}</span>
          </div>
        </div>
      </div>

      {code && (
        <div className="flex gap-4 text-xs font-mono text-gray-400 bg-[#0f1117] rounded px-3 py-2">
          <span>Set Wt: <span className="text-green-400">{setWt.toFixed(2)} kg</span></span>
          <span>Total Wt: <span className="text-green-400">{totalWt.toFixed(2)} kg</span></span>
        </div>
      )}

      <button onClick={addRow} disabled={!code || !date}
        className="px-4 py-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-40 text-white text-sm rounded font-medium transition-colors">
        + Add to List
      </button>

      {/* ── Pending list ── */}
      {rows.length > 0 && (
        <div>
          <div className="text-xs text-gray-400 font-mono uppercase tracking-widest mb-2">
            Pending — {rows.length} {rows.length === 1 ? 'entry' : 'entries'}
          </div>
          <div className="overflow-x-auto rounded-lg border border-[#2a2f3e]">
            <table className="w-full text-xs font-mono">
              <thead>
                <tr className="text-gray-500 border-b border-[#2a2f3e] bg-[#0f1117]">
                  {['Date','Code','Cover','Frame','Sets',''].map(h => (
                    <th key={h} className="px-3 py-1.5 text-left">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {rows.map(r => {
                  const w = getWeights(r.code);
                  const s = Math.min(r.cover, r.frame);
                  return (
                    <tr key={r.localId} className="border-b border-[#1e2433] hover:bg-[#1a1f2e]">
                      <td className="px-3 py-1.5 text-gray-400">{r.date}</td>
                      <td className="px-3 py-1.5 text-amber-400">{r.code}</td>
                      <td className="px-3 py-1.5 text-gray-300">{r.cover}</td>
                      <td className="px-3 py-1.5 text-gray-300">{r.frame}</td>
                      <td className="px-3 py-1.5 text-green-400 font-bold">{s}</td>
                      <td className="px-3 py-1.5">
                        <button onClick={() => removeRow(r.localId)} className="text-red-400 hover:text-red-300">✕</button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* ── Actions ── */}
      <div className="flex gap-2 pt-1">
        <button onClick={handleSubmit} disabled={rows.length === 0 || submitting}
          className="px-4 py-2 bg-green-600 hover:bg-green-500 disabled:opacity-40 text-white text-sm rounded font-medium transition-colors">
          {submitting ? 'Submitting…' : `Submit All (${rows.length})`}
        </button>
        <button onClick={onCancel}
          className="px-4 py-2 bg-[#2a2f3e] hover:bg-[#363d52] text-gray-300 text-sm rounded font-medium transition-colors">
          Cancel
        </button>
      </div>
    </div>
  );
}

// ─── SINGLE-ENTRY EDIT FORM (kept for editing existing rows) ──────────────────
interface ProdFormProps {
  initial: ProductionEntry;
  onSave: (date: string, code: string, cover: number, frame: number) => void;
  onCancel: () => void;
}

function ProductionEditForm({ initial, onSave, onCancel }: ProdFormProps) {
  const [date, setDate]   = useState(initial.date);
  const [code, setCode]   = useState(initial.code);
  const [cover, setCover] = useState(initial.coverQty);
  const [frame, setFrame] = useState(initial.frameQty);

  const weights = code ? getWeights(code) : undefined;
  const setQty  = Math.min(cover, frame);

  return (
    <div className="p-4 rounded-xl border border-amber-600/40 mb-4" style={{ background: '#151824' }}>
      <div className="text-xs text-amber-400 font-mono uppercase tracking-widest mb-3">Edit Entry</div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
        <div>
          <label className="text-xs text-gray-400 block mb-1">Date</label>
          <input type="date" value={date} onChange={e => setDate(e.target.value)}
            className="w-full bg-[#0f1117] border border-[#2a2f3e] rounded px-2 py-1.5 text-sm text-gray-200" />
        </div>
        <div className="col-span-3">
          <label className="text-xs text-gray-400 block mb-1">Product Code</label>
          <CodeSelect value={code} onChange={setCode}
            className="w-full bg-[#0f1117] border border-[#2a2f3e] rounded px-2 py-1.5 text-sm text-gray-200 font-mono" />
        </div>
      </div>
      {code && weights && (
        <div className="flex gap-4 mb-3 text-xs font-mono text-gray-400 bg-[#0f1117] rounded px-3 py-2">
          <span>Cover: <span className="text-amber-400">{weights.coverKg} kg</span></span>
          <span>Frame: <span className="text-amber-400">{weights.frameKg} kg</span></span>
          <span>Set: <span className="text-amber-400">{weights.setKg} kg</span></span>
        </div>
      )}
      <div className="grid grid-cols-3 gap-3 mb-3">
        <div>
          <label className="text-xs text-gray-400 block mb-1">Cover Qty</label>
          <input type="number" min={0} value={cover} onChange={e => setCover(Number(e.target.value))}
            className="w-full bg-[#0f1117] border border-[#2a2f3e] rounded px-2 py-1.5 text-sm text-gray-200 font-mono" />
        </div>
        <div>
          <label className="text-xs text-gray-400 block mb-1">Frame Qty</label>
          <input type="number" min={0} value={frame} onChange={e => setFrame(Number(e.target.value))}
            className="w-full bg-[#0f1117] border border-[#2a2f3e] rounded px-2 py-1.5 text-sm text-gray-200 font-mono" />
        </div>
        <div>
          <label className="text-xs text-gray-400 block mb-1">Sets <span className="text-gray-600">(auto)</span></label>
          <div className="px-2 py-1.5 rounded bg-[#0a0d12] border border-[#1e2433] text-sm font-mono text-amber-400">{setQty}</div>
        </div>
      </div>
      <div className="flex gap-2">
        <button onClick={() => { if (!code || !date) return; onSave(date, code, cover, frame); }}
          disabled={!code || !date}
          className="px-4 py-2 bg-green-600 hover:bg-green-500 disabled:opacity-40 text-white text-sm rounded font-medium">
          Save Update
        </button>
        <button onClick={onCancel}
          className="px-4 py-2 bg-[#2a2f3e] hover:bg-[#363d52] text-gray-300 text-sm rounded font-medium">
          Cancel
        </button>
      </div>
    </div>
  );
}

// ─── MAIN TAB ─────────────────────────────────────────────────────────────────
export function ProductionTab() {
  const { filteredProd, productionData, prodFilter, setProdFilter,
          addProduction, updateProduction, deleteProduction,
          importProductionCSV, productTypes, formatDate } = useData();

  const [showBatch, setShowBatch]   = useState(false);
  const [editId, setEditId]         = useState<string | null>(null);
  const [importResult, setImportResult] = useState<{ imported: number; skipped: string[] } | null>(null);
  const [filterItem, setFilterItem]     = useState<string[]>([]);
  const [confirmDelete, setConfirmDelete] = useState<string | null>(null);

  const displayRows = useMemo(() => filteredProd
    .filter(e => {
      if (filterItem.length === 0) return true;
      return filterItem.some(typeCode => {
        const pt = productTypes.find(t => t.code === typeCode);
        return pt ? e.code.startsWith(pt.prefix) : false;
      });
    })
    .sort((a, b) => b.date.localeCompare(a.date)),
  [filteredProd, filterItem, productTypes]);

  // KPIs
  const { totalSets, commSets, extraCovers, extraFrames } = useMemo(() => {
    const groups = new Map<string, { cover: number; frame: number; isComm: boolean }>();
    displayRows.forEach(e => {
      const k = e.code;
      if (!groups.has(k)) groups.set(k, { cover: 0, frame: 0, isComm: getCategoryFromCode(e.code) === 'commercial' });
      const r = groups.get(k)!;
      r.cover += e.coverQty;
      r.frame += e.frameQty;
    });
    let totalSets = 0, commSets = 0;
    groups.forEach(r => {
      const s = Math.min(r.cover, r.frame);
      totalSets += s;
      if (r.isComm) commSets += s;
    });
    const allGroups = new Map<string, { cover: number; frame: number }>();
    productionData.forEach(e => {
      const k = e.code;
      if (!allGroups.has(k)) allGroups.set(k, { cover: 0, frame: 0 });
      const r = allGroups.get(k)!;
      r.cover += e.coverQty;
      r.frame += e.frameQty;
    });
    let extraCovers = 0, extraFrames = 0;
    allGroups.forEach(r => {
      const s = Math.min(r.cover, r.frame);
      extraCovers += r.cover - s;
      extraFrames += r.frame - s;
    });
    return { totalSets, commSets, extraCovers, extraFrames };
  }, [displayRows, productionData]);

  const totalWt = displayRows.reduce((s, e) => s + e.totalWeightKg, 0);

  const chartData = useMemo(() => {
    const days: { label: string; value: number }[] = [];
    for (let i = 13; i >= 0; i--) {
      const d = new Date(Date.now() - i * 86400000);
      const iso = d.toISOString().split('T')[0];
      const label = `${d.getDate()}/${d.getMonth() + 1}`;
      const value = groupedSets(productionData.filter(e => e.date === iso));
      days.push({ label, value });
    }
    return days;
  }, [productionData]);

  function handleImport(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]; if (!file) return;
    const reader = new FileReader();
    reader.onload = ev => { setImportResult(importProductionCSV(ev.target?.result as string)); };
    reader.readAsText(file);
    e.target.value = '';
  }

  async function handleBatchSubmit(rows: PendingProdRow[]) {
    await Promise.all(rows.map(r => addProduction(r.date, r.code, r.cover, r.frame)));
    setShowBatch(false);
  }

  const editEntry = editId ? productionData.find(e => e.id === editId) : undefined;

  return (
    <div>
      {/* KPI Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5">
        <KpiCard label="Total Sets" value={totalSets.toLocaleString()} />
        <KpiCard label="Total Weight" value={`${(totalWt / 1000).toFixed(2)} T`} sub={`${totalWt.toLocaleString()} kg`} accent="#4ade80" />
        <KpiCard label="Commercial Sets" value={commSets.toLocaleString()} accent="#60a5fa" />
        <KpiCard label="Imbalance" value={`${extraCovers}C / ${extraFrames}F`}
          sub="Extra covers / frames" accent={extraCovers + extraFrames > 0 ? '#f59e0b' : '#4ade80'} />
      </div>

      {/* 14-day chart */}
      <div className="rounded-xl border border-[#2a2f3e] p-4 mb-5" style={{ background: '#151824' }}>
        <div className="text-xs text-gray-400 font-mono mb-2 uppercase tracking-widest">14-Day Production (Sets)</div>
        <BarChart data={chartData} color="#f59e0b" />
      </div>

      {/* Filters */}
      <div className="flex items-center gap-3 flex-wrap mb-4">
        <PeriodFilter filter={prodFilter} onChange={setProdFilter} />
        <div className="flex gap-1 flex-wrap">
          {productTypes.map(t => (
            <button key={t.code}
              onClick={() => setFilterItem(prev =>
                prev.includes(t.code) ? prev.filter(x => x !== t.code) : [...prev, t.code])}
              className={`px-2 py-0.5 rounded text-xs font-mono border transition-colors ${
                filterItem.includes(t.code) ? 'text-black border-transparent' : 'text-gray-400 border-[#2a2f3e] hover:border-gray-500'
              }`}
              style={filterItem.includes(t.code) ? { background: t.color } : {}}>
              {t.code}
            </button>
          ))}
          {filterItem.length > 0 && (
            <button onClick={() => setFilterItem([])}
              className="px-2 py-0.5 rounded text-xs text-gray-500 hover:text-gray-300 border border-[#2a2f3e]">
              Clear
            </button>
          )}
        </div>
      </div>

      {/* Toolbar */}
      <div className="flex gap-2 mb-4 flex-wrap">
        <button onClick={() => { setShowBatch(true); setEditId(null); }}
          disabled={showBatch}
          className="flex items-center gap-1.5 px-3 py-1.5 bg-amber-500 hover:bg-amber-400 disabled:opacity-50 text-black text-sm rounded font-medium transition-colors">
          <span>+</span> Add Production
        </button>
        <label className="flex items-center gap-1.5 px-3 py-1.5 bg-[#2a2f3e] hover:bg-[#363d52] text-gray-300 text-sm rounded font-medium cursor-pointer transition-colors">
          ↑ Import CSV
          <input type="file" accept=".csv" onChange={handleImport} className="hidden" />
        </label>
      </div>

      <ImportBanner result={importResult} onDismiss={() => setImportResult(null)} />

      {/* Batch Entry Panel */}
      {showBatch && !editId && (
        <BatchProductionPanel
          onSubmitAll={handleBatchSubmit}
          onCancel={() => setShowBatch(false)}
        />
      )}

      {/* Edit Form (single entry) */}
      {editId && editEntry && (
        <ProductionEditForm
          initial={editEntry}
          onSave={(date, code, cover, frame) => {
            updateProduction(editId, date, code, cover, frame);
            setEditId(null);
          }}
          onCancel={() => setEditId(null)}
        />
      )}

      {/* Delete confirmation */}
      {confirmDelete && (
        <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50">
          <div className="bg-[#151824] border border-[#2a2f3e] rounded-xl p-6 max-w-sm w-full mx-4">
            <div className="text-base font-semibold mb-2 text-white">Delete entry?</div>
            <div className="text-sm text-gray-400 mb-4">This cannot be undone.</div>
            <div className="flex gap-3">
              <button onClick={() => { deleteProduction(confirmDelete); setConfirmDelete(null); }}
                className="px-4 py-2 bg-red-600 hover:bg-red-500 text-white text-sm rounded">Delete</button>
              <button onClick={() => setConfirmDelete(null)}
                className="px-4 py-2 bg-[#2a2f3e] text-gray-300 text-sm rounded">Cancel</button>
            </div>
          </div>
        </div>
      )}

      {/* Table */}
      <div className="overflow-x-auto rounded-xl border border-[#2a2f3e]">
        <table className="w-full text-xs font-mono border-collapse">
          <thead>
            <tr className="text-gray-400 border-b border-[#2a2f3e]" style={{ background: '#1a1f2e' }}>
              {['Date','Code','Item','Size','Cap','Cover','Frame','Set','+Cover','+Frame','Set Wt (kg)','Total Wt (kg)',''].map(h => (
                <th key={h} className="px-3 py-2 text-left whitespace-nowrap">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {displayRows.length === 0 && (
              <tr><td colSpan={13} className="px-4 py-8 text-center text-gray-600">No entries for selected period</td></tr>
            )}
            {displayRows.map(e => (
              <tr key={e.id} className="border-b border-[#1e2433] transition-colors hover:bg-[#1a1f2e]">
                <td className="px-3 py-1.5 text-gray-400">{formatDate(e.date)}</td>
                <td className="px-3 py-1.5 text-amber-400">{e.code}</td>
                <td className="px-3 py-1.5 text-gray-300">{e.item}</td>
                <td className="px-3 py-1.5 text-gray-400">{e.size}</td>
                <td className="px-3 py-1.5 text-gray-400">{e.capacity}</td>
                <td className="px-3 py-1.5 text-gray-300">{e.coverQty}</td>
                <td className="px-3 py-1.5 text-gray-300">{e.frameQty}</td>
                <td className="px-3 py-1.5 text-green-400 font-bold">{e.setQty}</td>
                <td className={`px-3 py-1.5 ${e.extraCover > 0 ? 'text-amber-400 font-bold' : 'text-gray-600'}`}>{e.extraCover}</td>
                <td className={`px-3 py-1.5 ${e.extraFrame > 0 ? 'text-amber-400 font-bold' : 'text-gray-600'}`}>{e.extraFrame}</td>
                <td className="px-3 py-1.5 text-gray-300">{e.setWeightKg.toFixed(2)}</td>
                <td className="px-3 py-1.5 text-gray-300">{e.totalWeightKg.toFixed(2)}</td>
                <td className="px-3 py-1.5">
                  <div className="flex gap-2">
                    <button onClick={() => { setEditId(e.id); setShowBatch(false); }}
                      className="text-blue-400 hover:text-blue-300 text-xs">Edit</button>
                    <button onClick={() => setConfirmDelete(e.id)}
                      className="text-red-400 hover:text-red-300 text-xs">Del</button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="mt-2 text-xs text-gray-600 font-mono text-right">{displayRows.length} entries</div>
    </div>
  );
}
