// Generated by build-dashboard skill — production
// 5-tab production dashboard shell

import { useState, createContext, useContext } from 'react';
import { useProductionData, ProductionDataContext, Toast } from './useProductionData';
import { ProductionTab } from './ProductionTab';
import { DispatchTab } from './DispatchTab';
import { StockTab } from './StockTab';
import { RawMaterialsTab } from './RawMaterialsTab';
import { MonthlyOverviewTab } from './MonthlyOverviewTab';
import { SettingsPanel } from './SettingsPanel';

// ─── CONTEXT ──────────────────────────────────────────────────────────────────
export const DataContext = createContext<ProductionDataContext | null>(null);
export function useData(): ProductionDataContext {
  const ctx = useContext(DataContext);
  if (!ctx) throw new Error('useData must be inside ProductionDashboard');
  return ctx;
}

// ─── TYPES ────────────────────────────────────────────────────────────────────
type MainTab = 'production' | 'dispatch' | 'stock' | 'rawmaterials' | 'monthly';

const MAIN_TABS: { id: MainTab; label: string }[] = [
  { id: 'production',   label: 'Production' },
  { id: 'dispatch',     label: 'Dispatch' },
  { id: 'stock',        label: 'Stock' },
  { id: 'rawmaterials', label: 'Raw Materials' },
  { id: 'monthly',      label: 'Monthly Overview' },
];

// ─── STYLES ───────────────────────────────────────────────────────────────────
const S = {
  shell:       'min-h-screen font-sans text-gray-100',
  header:      'flex items-center justify-between px-6 py-4 border-b border-[#2a2f3e] bg-[#151824]',
  logo:        'text-lg font-bold tracking-tight text-white font-mono',
  logoSub:     'text-xs text-amber-400 font-mono ml-2',
  tabBar:      'flex items-center gap-1 px-4 pt-3 bg-[#151824] border-b border-[#2a2f3e] overflow-x-auto',
  tab:         'px-4 py-2 text-sm font-medium rounded-t-md cursor-pointer whitespace-nowrap transition-colors',
  tabActive:   'bg-[#0f1117] text-amber-400 border-b-2 border-amber-400',
  tabInactive: 'text-gray-400 hover:text-gray-200',
  content:     'p-5',
  gear:        'p-2 rounded-md hover:bg-[#2a2f3e] transition cursor-pointer text-gray-400 hover:text-amber-400',
};

// ─── TOAST NOTIFICATIONS ──────────────────────────────────────────────────────
function ToastContainer({ toasts, onDismiss }: { toasts: Toast[]; onDismiss: (id: string) => void }) {
  if (toasts.length === 0) return null;
  const colors = {
    error: 'bg-red-900/90 border-red-700 text-red-200',
    warn:  'bg-amber-900/90 border-amber-700 text-amber-200',
    success: 'bg-green-900/90 border-green-700 text-green-200',
  };
  return (
    <div className="fixed top-4 right-4 z-50 flex flex-col gap-2 max-w-sm">
      {toasts.map(t => (
        <div key={t.id} className={`${colors[t.type]} border rounded-lg px-4 py-3 text-sm font-mono shadow-lg flex items-start gap-2`}>
          <span className="flex-1">{t.message}</span>
          <button onClick={() => onDismiss(t.id)} className="text-xs opacity-60 hover:opacity-100 mt-0.5">✕</button>
        </div>
      ))}
    </div>
  );
}

// ─── COMPONENT ────────────────────────────────────────────────────────────────
export default function ProductionDashboard() {
  const data = useProductionData();
  const [activeTab, setActiveTab] = useState<MainTab>('production');
  const [showSettings, setShowSettings] = useState(false);

  // ── Loading / Error screens ──────────────────────────────────────────────
  if (data.loading) {
    return (
      <div className="min-h-screen flex items-center justify-center font-mono" style={{ background: '#0f1117' }}>
        <div className="text-center">
          <div className="w-8 h-8 border-2 border-amber-400 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <p className="text-amber-400 text-sm">Loading dashboard data…</p>
        </div>
      </div>
    );
  }

  if (data.error) {
    return (
      <div className="min-h-screen flex items-center justify-center font-mono" style={{ background: '#0f1117' }}>
        <div className="text-center max-w-md px-6">
          <p className="text-red-400 text-sm mb-2 font-bold">Failed to load data</p>
          <p className="text-gray-400 text-xs">{data.error}</p>
          <p className="text-gray-500 text-xs mt-4">Check your Supabase credentials in .env.local and ensure the database tables exist.</p>
        </div>
      </div>
    );
  }

  return (
    <DataContext.Provider value={data}>
      <div className={S.shell} style={{ background: '#0f1117' }}>
        <ToastContainer toasts={data.toasts} onDismiss={data.dismissToast} />

        {/* ── Header ── */}
        <div className={S.header}>
          <div className="flex items-center">
            <span className={S.logo}>FRP PRODUCTION</span>
            <span className={S.logoSub}>DASHBOARD</span>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-xs text-gray-500 font-mono">{new Date().toLocaleDateString('en-GB')}</span>
            <button
              onClick={() => setShowSettings(true)}
              className={S.gear}
              title="Settings"
            >
              <svg width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                <path d="M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1Z"/>
              </svg>
            </button>
          </div>
        </div>

        {/* ── Tab Bar ── */}
        <div className={S.tabBar}>
          {MAIN_TABS.map(t => (
            <button
              key={t.id}
              onClick={() => setActiveTab(t.id)}
              className={`${S.tab} ${activeTab === t.id ? S.tabActive : S.tabInactive}`}
            >
              {t.label}
            </button>
          ))}
        </div>

        {/* ── Tab Content ── */}
        <div className={S.content}>
          {activeTab === 'production'   && <ProductionTab />}
          {activeTab === 'dispatch'     && <DispatchTab />}
          {activeTab === 'stock'        && <StockTab />}
          {activeTab === 'rawmaterials' && <RawMaterialsTab />}
          {activeTab === 'monthly'      && <MonthlyOverviewTab />}
        </div>

        {/* ── Settings Modal ── */}
        {showSettings && (
          <SettingsPanel onClose={() => setShowSettings(false)} />
        )}
      </div>
    </DataContext.Provider>
  );
}

