// Generated by build-dashboard skill — production
// Raw Materials Tab: 3 sub-tabs — Daily Consumption, Full Ledger, Monthly Summary

import { useState, useMemo } from 'react';
import { useData } from './ProductionDashboard';
import { RAW_MATERIALS } from './productCatalog';

function fmt(n: number, dec = 0) { return n.toLocaleString(undefined, { minimumFractionDigits: dec, maximumFractionDigits: dec }); }
function today() { return new Date().toISOString().slice(0, 10); }
function monthKey(d: string) { return d.slice(0, 7); }
function lastNMonths(n: number): string[] {
  const now = new Date(); const out: string[] = [];
  for (let i = n - 1; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    out.push(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`);
  }
  return out;
}

const S = {
  card:       'bg-[#1a1f2e] border border-[#2a2f3e] rounded-lg p-4',
  label:      'text-xs text-gray-400 font-mono uppercase tracking-wide mb-1',
  val:        'text-2xl font-bold font-mono text-white',
  sub:        'text-xs text-gray-500 mt-0.5',
  btn:        'px-3 py-1.5 rounded-md text-sm font-medium transition-colors',
  btnPrimary: 'bg-amber-500 text-black hover:bg-amber-400',
  btnGhost:   'bg-[#2a2f3e] text-gray-300 hover:bg-[#363d52]',
  input:      'w-full bg-[#0f1117] border border-[#2a2f3e] rounded px-3 py-1.5 text-sm text-white placeholder-gray-600 focus:outline-none focus:border-amber-500',
  th:         'text-left text-xs text-gray-400 font-mono uppercase px-3 py-2 border-b border-[#2a2f3e]',
  td:         'px-3 py-2 text-sm',
  pill:       'px-3 py-1.5 rounded-full text-sm font-medium transition-colors',
};

type SubTab = 'daily' | 'ledger' | 'monthly';

// ─── FORM ──────────────────────────────────────────────────────────────────────
interface FormState {
  date: string;
  material: string;
  category: 'INWARD' | 'OUTWARD';
  department: 'PRODUCTION' | 'FINISHING';
  qty: string;
}
const EMPTY: FormState = { date: today(), material: '', category: 'OUTWARD', department: 'PRODUCTION', qty: '' };

function RawMaterialForm() {
  const { addRawMaterial, importRawMaterialCSV } = useData();
  const [form, setForm] = useState<FormState>(EMPTY);
  const [saved, setSaved] = useState(false);
  const [importResult, setImportResult] = useState<string | null>(null);

  const selectedMat = RAW_MATERIALS.find(m => m.name === form.material);
  const unit = selectedMat?.unit ?? '';
  const weightT = selectedMat ? selectedMat.weightPerUnitT * Number(form.qty) : 0;

  function setF(k: keyof FormState, v: string) { setForm(f => ({ ...f, [k]: v })); }

  function handleMaterialChange(name: string) {
    const mat = RAW_MATERIALS.find(m => m.name === name);
    const dept = mat?.department === 'FINISHING' ? 'FINISHING' : 'PRODUCTION';
    setForm(f => ({ ...f, material: name, department: dept }));
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const mat = RAW_MATERIALS.find(m => m.name === form.material);
    addRawMaterial(form.date, form.material, form.category, form.department, mat?.unit ?? '', Number(form.qty));
    setForm(EMPTY); setSaved(true); setTimeout(() => setSaved(false), 2000);
  }

  function handleCSV(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]; if (!file) return;
    const reader = new FileReader();
    reader.onload = ev => {
      const r = importRawMaterialCSV(ev.target?.result as string);
      setImportResult(`Imported ${r.imported} rows${r.skipped.length ? `, skipped ${r.skipped.length}` : ''}`);
      setTimeout(() => setImportResult(null), 4000);
    };
    reader.readAsText(file); e.target.value = '';
  }

  return (
    <div className={S.card}>
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-semibold text-amber-400 font-mono uppercase tracking-wide">Log Raw Material</h3>
        <label className={`${S.btn} ${S.btnGhost} cursor-pointer text-xs`}>
          Import CSV <input type="file" accept=".csv" className="hidden" onChange={handleCSV} />
        </label>
      </div>
      {importResult && <div className="mb-3 text-xs text-green-400 font-mono bg-green-900/20 rounded px-2 py-1">{importResult}</div>}
      <form onSubmit={handleSubmit} className="grid grid-cols-2 gap-3 md:grid-cols-3">
        <div>
          <label className={S.label}>Date</label>
          <input type="date" className={S.input} value={form.date} onChange={e => setF('date', e.target.value)} required />
        </div>
        <div>
          <label className={S.label}>Material</label>
          <input list="rm-list" className={S.input} value={form.material}
            onChange={e => handleMaterialChange(e.target.value)} placeholder="Select material..." required />
          <datalist id="rm-list">{RAW_MATERIALS.map(m => <option key={m.name} value={m.name}>{m.name} ({m.unit})</option>)}</datalist>
          {unit && <div className="text-xs text-gray-500 mt-0.5 font-mono">Unit: {unit}</div>}
        </div>
        <div>
          <label className={S.label}>Qty ({unit || 'units'})</label>
          <input type="number" min="0" step="any" className={S.input}
            value={form.qty} onChange={e => setF('qty', e.target.value)} required />
          {weightT > 0 && <div className="text-xs text-amber-400 mt-0.5 font-mono">{weightT.toFixed(3)} T</div>}
        </div>
        <div>
          <label className={S.label}>In / Out</label>
          <select className={S.input} value={form.category} onChange={e => setF('category', e.target.value as 'INWARD' | 'OUTWARD')}>
            <option value="OUTWARD">Outward (used)</option>
            <option value="INWARD">Inward (received)</option>
          </select>
        </div>
        <div>
          <label className={S.label}>Department</label>
          <select className={S.input} value={form.department} onChange={e => setF('department', e.target.value as 'PRODUCTION' | 'FINISHING')}>
            <option value="PRODUCTION">Production</option>
            <option value="FINISHING">Finishing</option>
          </select>
        </div>
        <div className="flex items-end">
          <button type="submit" className={`${S.btn} ${S.btnPrimary} w-full`}>
            {saved ? 'Saved!' : 'Log Entry'}
          </button>
        </div>
      </form>
    </div>
  );
}

// ─── DAILY CONSUMPTION ─────────────────────────────────────────────────────────
function DailyConsumptionTab() {
  const { rawMaterialData } = useData();
  const [selectedDate, setSelectedDate] = useState(today());

  const dayEntries = rawMaterialData.filter(r => r.date === selectedDate && r.category === 'OUTWARD');

  const byMaterial = useMemo(() => {
    const m = new Map<string, { qty: number; weightT: number; unit: string; dept: string }>();
    dayEntries.forEach(r => {
      const prev = m.get(r.material) ?? { qty: 0, weightT: 0, unit: r.unit, dept: r.department };
      m.set(r.material, { qty: prev.qty + r.qty, weightT: prev.weightT + r.weightT, unit: r.unit, dept: r.department });
    });
    return Array.from(m.entries()).sort((a, b) => a[0].localeCompare(b[0]));
  }, [dayEntries]);

  const totalWeight = byMaterial.reduce((a, [, v]) => a + v.weightT, 0);

  function prevDay() { const d = new Date(selectedDate); d.setDate(d.getDate() - 1); setSelectedDate(d.toISOString().slice(0, 10)); }
  function nextDay() { const d = new Date(selectedDate); d.setDate(d.getDate() + 1); setSelectedDate(d.toISOString().slice(0, 10)); }

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <button onClick={prevDay} className={`${S.btn} ${S.btnGhost} text-xs px-2`}>←</button>
        <input type="date" className={`${S.input} w-40`} value={selectedDate} onChange={e => setSelectedDate(e.target.value)} />
        <button onClick={nextDay} className={`${S.btn} ${S.btnGhost} text-xs px-2`}>→</button>
        <span className="text-xs text-gray-500 font-mono">{dayEntries.length} entries — {totalWeight.toFixed(3)} T used</span>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {(['PRODUCTION', 'FINISHING'] as const).map(dept => {
          const items = byMaterial.filter(([, v]) => v.dept === dept);
          const wt = items.reduce((a, [, v]) => a + v.weightT, 0);
          return (
            <div key={dept} className={S.card}>
              <div className={S.label}>{dept}</div>
              <div className={`${S.val} text-lg`}>{wt.toFixed(3)} T</div>
              <div className={S.sub}>{items.length} materials</div>
            </div>
          );
        })}
        <div className={S.card}>
          <div className={S.label}>Total Used</div>
          <div className={`${S.val} text-lg text-amber-400`}>{totalWeight.toFixed(3)} T</div>
        </div>
        <div className={S.card}>
          <div className={S.label}>Entries</div>
          <div className={`${S.val} text-lg`}>{dayEntries.length}</div>
        </div>
      </div>

      <RawMaterialForm />

      <div className={S.card}>
        <div className={S.label + ' mb-3'}>Consumption — {selectedDate}</div>
        {byMaterial.length === 0 ? (
          <div className="text-gray-500 text-sm py-4 text-center">No outward entries for this date</div>
        ) : (
          <table className="w-full text-sm">
            <thead>
              <tr>{['Material','Unit','Qty','Weight (T)','Dept'].map(h => <th key={h} className={S.th}>{h}</th>)}</tr>
            </thead>
            <tbody>
              {byMaterial.map(([name, v]) => (
                <tr key={name} className="border-b border-[#1e2436] hover:bg-[#1e2436]/40">
                  <td className={`${S.td} font-medium text-white`}>{name}</td>
                  <td className={`${S.td} text-gray-400`}>{v.unit}</td>
                  <td className={`${S.td} font-mono text-amber-400`}>{fmt(v.qty, 2)}</td>
                  <td className={`${S.td} font-mono text-green-400`}>{v.weightT.toFixed(3)}</td>
                  <td className={`${S.td} text-xs text-gray-400`}>{v.dept}</td>
                </tr>
              ))}
              <tr>
                <td colSpan={3} className="px-3 py-2 text-right text-xs text-gray-400 font-mono">Total</td>
                <td className="px-3 py-2 font-mono font-bold text-amber-400">{totalWeight.toFixed(3)}</td>
                <td />
              </tr>
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}

// ─── FULL LEDGER ───────────────────────────────────────────────────────────────
function FullLedgerTab() {
  const { rawMaterialData, deleteRawMaterial } = useData();
  const [search, setSearch]         = useState('');
  const [filterDept, setFilterDept] = useState<'all' | 'PRODUCTION' | 'FINISHING'>('all');
  const [filterCat, setFilterCat]   = useState<'all' | 'INWARD' | 'OUTWARD'>('all');

  const filtered = useMemo(() => {
    let list = [...rawMaterialData].sort((a, b) => b.date.localeCompare(a.date));
    if (search)           list = list.filter(r => r.material.toLowerCase().includes(search.toLowerCase()));
    if (filterDept !== 'all') list = list.filter(r => r.department === filterDept);
    if (filterCat !== 'all')  list = list.filter(r => r.category === filterCat);
    return list;
  }, [rawMaterialData, search, filterDept, filterCat]);

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap gap-2">
        <input className={`${S.input} max-w-xs text-xs`} placeholder="Search material..."
          value={search} onChange={e => setSearch(e.target.value)} />
        <select className={`${S.input} w-auto text-xs`} value={filterDept} onChange={e => setFilterDept(e.target.value as typeof filterDept)}>
          <option value="all">All Departments</option>
          <option value="PRODUCTION">Production</option>
          <option value="FINISHING">Finishing</option>
        </select>
        <select className={`${S.input} w-auto text-xs`} value={filterCat} onChange={e => setFilterCat(e.target.value as typeof filterCat)}>
          <option value="all">Inward + Outward</option>
          <option value="OUTWARD">Outward only</option>
          <option value="INWARD">Inward only</option>
        </select>
        <span className="text-xs text-gray-500 font-mono ml-auto self-center">{filtered.length} entries</span>
      </div>

      <RawMaterialForm />

      <div className={S.card}>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr>{['Date','Material','Cat.','Qty','Unit','Weight (T)','Dept',''].map(h => <th key={h} className={S.th}>{h}</th>)}</tr>
            </thead>
            <tbody>
              {filtered.length === 0 && <tr><td colSpan={8} className="px-3 py-8 text-center text-gray-500">No entries</td></tr>}
              {filtered.map(r => (
                <tr key={r.id} className={`border-b border-[#1e2436] hover:bg-[#1e2436]/40 ${r.category === 'INWARD' ? 'bg-green-950/10' : ''}`}>
                  <td className={`${S.td} font-mono text-gray-400 text-xs`}>{r.date}</td>
                  <td className={`${S.td} text-white`}>{r.material}</td>
                  <td className={`${S.td} text-xs`}>
                    <span className={`px-1.5 py-0.5 rounded font-mono text-xs ${r.category === 'INWARD' ? 'bg-green-900/40 text-green-300' : 'bg-orange-900/40 text-orange-300'}`}>
                      {r.category}
                    </span>
                  </td>
                  <td className={`${S.td} font-mono text-amber-400`}>{fmt(r.qty, 2)}</td>
                  <td className={`${S.td} text-xs text-gray-400`}>{r.unit}</td>
                  <td className={`${S.td} font-mono text-green-400`}>{r.weightT > 0 ? r.weightT.toFixed(3) : '—'}</td>
                  <td className={`${S.td} text-xs text-gray-400`}>{r.department}</td>
                  <td className={S.td}>
                    <button onClick={() => deleteRawMaterial(r.id)} className="text-xs text-red-400 hover:text-red-300">Del</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

// ─── MONTHLY SUMMARY ───────────────────────────────────────────────────────────
function MonthlySummaryTab() {
  const { rawMaterialData } = useData();
  const months = lastNMonths(6);

  const allMaterials = useMemo(() => {
    const names = new Set(rawMaterialData.filter(r => r.category === 'OUTWARD').map(r => r.material));
    return Array.from(names).sort();
  }, [rawMaterialData]);

  const monthData = useMemo(() => {
    return months.map(m => {
      const entries = rawMaterialData.filter(r => monthKey(r.date) === m && r.category === 'OUTWARD');
      const byMat: Record<string, { qty: number; weightT: number }> = {};
      entries.forEach(r => {
        if (!byMat[r.material]) byMat[r.material] = { qty: 0, weightT: 0 };
        byMat[r.material].qty += r.qty;
        byMat[r.material].weightT += r.weightT;
      });
      const totalT = Object.values(byMat).reduce((a, v) => a + v.weightT, 0);
      return { month: m, byMat, totalT, entryCount: entries.length };
    });
  }, [rawMaterialData, months]);

  const latest = monthData[monthData.length - 1];
  const prev   = monthData[monthData.length - 2];
  const trend  = prev?.totalT > 0 ? ((latest.totalT - prev.totalT) / prev.totalT * 100) : 0;

  return (
    <div className="space-y-5">
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className={S.card}>
          <div className={S.label}>This Month (outward)</div>
          <div className={S.val}>{latest.totalT.toFixed(2)} T</div>
          {trend !== 0 && <div className={`text-xs mt-0.5 ${trend >= 0 ? 'text-red-400' : 'text-green-400'}`}>{trend >= 0 ? '+' : ''}{trend.toFixed(1)}% vs prev</div>}
        </div>
        <div className={S.card}>
          <div className={S.label}>Materials Tracked</div>
          <div className={`${S.val} text-amber-400`}>{allMaterials.length}</div>
        </div>
        <div className={S.card}>
          <div className={S.label}>Entries This Month</div>
          <div className={`${S.val} text-purple-400`}>{latest.entryCount}</div>
        </div>
        <div className={S.card}>
          <div className={S.label}>6-Month Total</div>
          <div className={`${S.val} text-blue-400`}>{monthData.reduce((a, m) => a + m.totalT, 0).toFixed(2)} T</div>
        </div>
      </div>

      <div className={S.card}>
        <div className={S.label + ' mb-3'}>Monthly Consumption (T)</div>
        <div className="flex items-end gap-4 h-24">
          {monthData.map(m => {
            const maxT = Math.max(...monthData.map(x => x.totalT), 1);
            const pct  = (m.totalT / maxT) * 100;
            return (
              <div key={m.month} className="flex flex-col items-center flex-1 gap-1">
                <span className="text-xs font-mono text-gray-400">{m.totalT.toFixed(1)}</span>
                <div className="w-full rounded-t bg-amber-500 opacity-80" style={{ height: `${Math.max(pct * 0.7, 2)}px`, minHeight: '2px' }} />
                <span className="text-xs text-gray-500">{m.month.slice(5)}</span>
              </div>
            );
          })}
        </div>
      </div>

      <div className={S.card}>
        <div className={S.label + ' mb-3'}>Material × Month (qty used)</div>
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr>
                <th className={S.th + ' text-xs'}>Material</th>
                <th className={S.th + ' text-xs'}>Unit</th>
                {months.map(m => <th key={m} className={S.th + ' text-xs text-center'}>{m.slice(5)}</th>)}
              </tr>
            </thead>
            <tbody>
              {allMaterials.map(name => {
                const mat = RAW_MATERIALS.find(m => m.name === name);
                return (
                  <tr key={name} className="border-b border-[#1e2436] hover:bg-[#1e2436]/40">
                    <td className={`${S.td} text-white text-xs`}>{name}</td>
                    <td className={`${S.td} text-gray-400 text-xs`}>{mat?.unit ?? ''}</td>
                    {monthData.map(md => {
                      const v = md.byMat[name];
                      return (
                        <td key={md.month} className={`${S.td} font-mono text-xs text-center`}>
                          {v ? <span className="text-amber-400">{fmt(v.qty, 1)}</span> : <span className="text-gray-600">—</span>}
                        </td>
                      );
                    })}
                  </tr>
                );
              })}
              <tr className="bg-[#1e2436]">
                <td className={`${S.td} text-xs font-bold text-white`} colSpan={2}>Total (T)</td>
                {monthData.map(md => (
                  <td key={md.month} className={`${S.td} font-mono font-bold text-xs text-center text-amber-400`}>{md.totalT.toFixed(2)}</td>
                ))}
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

// ─── MAIN ──────────────────────────────────────────────────────────────────────
export function RawMaterialsTab() {
  const [subTab, setSubTab] = useState<SubTab>('daily');
  const SUB_TABS: { id: SubTab; label: string }[] = [
    { id: 'daily',   label: 'Daily Consumption' },
    { id: 'ledger',  label: 'Full Ledger' },
    { id: 'monthly', label: 'Monthly Summary' },
  ];
  return (
    <div>
      <div className="flex gap-2 mb-5">
        {SUB_TABS.map(t => (
          <button key={t.id} onClick={() => setSubTab(t.id)}
            className={`${S.pill} ${subTab === t.id ? 'bg-amber-500 text-black' : 'bg-[#2a2f3e] text-gray-300 hover:bg-[#363d52]'}`}>
            {t.label}
          </button>
        ))}
      </div>
      {subTab === 'daily'   && <DailyConsumptionTab />}
      {subTab === 'ledger'  && <FullLedgerTab />}
      {subTab === 'monthly' && <MonthlySummaryTab />}
    </div>
  );
}
