// Generated by build-dashboard skill — production
// Settings Panel: extensible product types, sizes, capacities

import { useState } from 'react';
import { useData } from './ProductionDashboard';
import { COLORS } from './productCatalog';

const S = {
  overlay:    'fixed inset-0 bg-black/60 z-50 flex items-start justify-end',
  panel:      'h-full w-full max-w-lg bg-[#151824] border-l border-[#2a2f3e] flex flex-col shadow-2xl',
  header:     'flex items-center justify-between px-5 py-4 border-b border-[#2a2f3e]',
  title:      'text-sm font-bold text-amber-400 font-mono uppercase tracking-wide',
  body:       'flex-1 overflow-y-auto p-5 space-y-6',
  section:    'bg-[#1a1f2e] border border-[#2a2f3e] rounded-lg p-4',
  sectionTitle:'text-xs font-semibold text-gray-300 font-mono uppercase tracking-wide mb-3',
  label:      'text-xs text-gray-400 font-mono uppercase tracking-wide mb-1',
  input:      'w-full bg-[#0f1117] border border-[#2a2f3e] rounded px-3 py-1.5 text-sm text-white placeholder-gray-600 focus:outline-none focus:border-amber-500',
  btn:        'px-3 py-1.5 rounded-md text-sm font-medium transition-colors',
  btnPrimary: 'bg-amber-500 text-black hover:bg-amber-400',
  btnGhost:   'bg-[#2a2f3e] text-gray-300 hover:bg-[#363d52]',
  btnDanger:  'text-red-400 hover:text-red-300 text-xs',
  chip:       'flex items-center gap-1.5 px-2 py-1 rounded text-xs font-mono border',
  tag:        'inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs font-mono',
};

interface Props { onClose: () => void; }

// ─── PRODUCT TYPES SECTION ─────────────────────────────────────────────────────
function ProductTypesSection() {
  const { productTypes, addProductType } = useData();
  const [form, setForm] = useState({ code: '', prefix: '', label: '', category: 'regular' as 'commercial' | 'regular', color: '#60a5fa' });
  const [err, setErr] = useState('');

  function handleAdd() {
    if (!form.code.trim() || !form.prefix.trim() || !form.label.trim()) { setErr('All fields required'); return; }
    if (productTypes.find(t => t.code === form.code.toUpperCase())) { setErr('Code already exists'); return; }
    addProductType({ code: form.code.toUpperCase(), prefix: form.prefix.toLowerCase(), label: form.label, category: form.category, color: form.color, itemCodes: [form.code.toUpperCase()] });
    setForm({ code: '', prefix: '', label: '', category: 'regular', color: '#60a5fa' });
    setErr('');
  }

  return (
    <div className={S.section}>
      <div className={S.sectionTitle}>Product Types</div>
      <div className="flex flex-wrap gap-2 mb-4">
        {productTypes.map(t => (
          <span key={t.code} className={S.chip} style={{ color: t.color, borderColor: `${t.color}40`, background: `${t.color}10` }}>
            <span className="font-bold">{t.code}</span>
            <span className="text-gray-400">·</span>
            <span>{t.label}</span>
            <span className="text-gray-500 text-[10px]">[{t.category[0].toUpperCase()}]</span>
          </span>
        ))}
      </div>
      <div className="border-t border-[#2a2f3e] pt-3">
        <div className="text-xs text-gray-400 mb-2">Add new type</div>
        <div className="grid grid-cols-2 gap-2">
          <div>
            <label className={S.label}>Code (e.g. MHC)</label>
            <input className={S.input} value={form.code} onChange={e => setForm(f => ({ ...f, code: e.target.value }))} placeholder="CODE" />
          </div>
          <div>
            <label className={S.label}>Prefix (e.g. m_)</label>
            <input className={S.input} value={form.prefix} onChange={e => setForm(f => ({ ...f, prefix: e.target.value }))} placeholder="x_" />
          </div>
          <div className="col-span-2">
            <label className={S.label}>Label</label>
            <input className={S.input} value={form.label} onChange={e => setForm(f => ({ ...f, label: e.target.value }))} placeholder="e.g. Manhole Cover" />
          </div>
          <div>
            <label className={S.label}>Category</label>
            <select className={S.input} value={form.category} onChange={e => setForm(f => ({ ...f, category: e.target.value as any }))}>
              <option value="commercial">Commercial</option>
              <option value="regular">Regular</option>
            </select>
          </div>
          <div>
            <label className={S.label}>Badge Color</label>
            <div className="flex gap-2 items-center">
              <input type="color" className="h-9 w-12 rounded border border-[#2a2f3e] bg-[#0f1117] cursor-pointer" value={form.color} onChange={e => setForm(f => ({ ...f, color: e.target.value }))} />
              <span className="text-xs font-mono text-gray-400">{form.color}</span>
            </div>
          </div>
        </div>
        {err && <div className="text-xs text-red-400 mt-2">{err}</div>}
        <button onClick={handleAdd} className={`${S.btn} ${S.btnPrimary} mt-3 text-xs`}>Add Type</button>
      </div>
    </div>
  );
}

// ─── PRODUCT SIZES SECTION ─────────────────────────────────────────────────────
function ProductSizesSection() {
  const { productSizes, addProductSize } = useData();
  const [form, setForm] = useState({ value: '', label: '', category: 'regular' as 'commercial' | 'regular' });
  const [err, setErr] = useState('');

  const commercial = productSizes.filter(s => s.category === 'commercial');
  const regular    = productSizes.filter(s => s.category === 'regular');

  function handleAdd() {
    if (!form.value.trim() || !form.label.trim()) { setErr('Value and label required'); return; }
    if (productSizes.find(s => s.value === form.value)) { setErr('Size already exists'); return; }
    addProductSize({ value: form.value, label: form.label, category: form.category });
    setForm({ value: '', label: '', category: 'regular' });
    setErr('');
  }

  return (
    <div className={S.section}>
      <div className={S.sectionTitle}>Product Sizes / Dimensions</div>

      <div className="mb-2">
        <div className="text-xs text-blue-400 font-mono mb-1">Commercial ({commercial.length})</div>
        <div className="flex flex-wrap gap-1">
          {commercial.map(s => (
            <span key={s.value} className="text-xs px-2 py-0.5 rounded font-mono bg-blue-900/30 text-blue-300 border border-blue-800/40">{s.label}</span>
          ))}
        </div>
      </div>
      <div className="mb-4">
        <div className="text-xs text-green-400 font-mono mb-1">Regular ({regular.length})</div>
        <div className="flex flex-wrap gap-1">
          {regular.map(s => (
            <span key={s.value} className="text-xs px-2 py-0.5 rounded font-mono bg-green-900/30 text-green-300 border border-green-800/40">{s.label}</span>
          ))}
        </div>
      </div>

      <div className="border-t border-[#2a2f3e] pt-3">
        <div className="text-xs text-gray-400 mb-2">Add new size</div>
        <div className="grid grid-cols-2 gap-2">
          <div>
            <label className={S.label}>Value (code key)</label>
            <input className={S.input} value={form.value} onChange={e => setForm(f => ({ ...f, value: e.target.value }))} placeholder="e.g. 450*600" />
          </div>
          <div>
            <label className={S.label}>Display Label</label>
            <input className={S.input} value={form.label} onChange={e => setForm(f => ({ ...f, label: e.target.value }))} placeholder="e.g. 450×600 mm" />
          </div>
          <div>
            <label className={S.label}>Category</label>
            <select className={S.input} value={form.category} onChange={e => setForm(f => ({ ...f, category: e.target.value as any }))}>
              <option value="commercial">Commercial (inches)</option>
              <option value="regular">Regular (mm)</option>
            </select>
          </div>
        </div>
        {err && <div className="text-xs text-red-400 mt-2">{err}</div>}
        <button onClick={handleAdd} className={`${S.btn} ${S.btnPrimary} mt-3 text-xs`}>Add Size</button>
      </div>
    </div>
  );
}

// ─── CAPACITIES SECTION ────────────────────────────────────────────────────────
function CapacitiesSection() {
  const { capacities, addCapacity } = useData();
  const [form, setForm] = useState({ value: '', label: '' });
  const [err, setErr] = useState('');

  function handleAdd() {
    if (!form.value.trim()) { setErr('Value required'); return; }
    if (capacities.find(c => c.value === form.value)) { setErr('Capacity already exists'); return; }
    addCapacity({ value: form.value, label: form.label || form.value });
    setForm({ value: '', label: '' });
    setErr('');
  }

  return (
    <div className={S.section}>
      <div className={S.sectionTitle}>Load Capacities</div>
      <div className="flex flex-wrap gap-1 mb-4">
        {capacities.map(c => (
          <span key={c.value} className="text-xs px-2 py-0.5 rounded font-mono bg-amber-900/30 text-amber-300 border border-amber-800/40">{c.label}</span>
        ))}
      </div>
      <div className="border-t border-[#2a2f3e] pt-3">
        <div className="text-xs text-gray-400 mb-2">Add new capacity</div>
        <div className="grid grid-cols-2 gap-2">
          <div>
            <label className={S.label}>Value (used in code)</label>
            <input className={S.input} value={form.value} onChange={e => setForm(f => ({ ...f, value: e.target.value }))} placeholder="e.g. 50T" />
          </div>
          <div>
            <label className={S.label}>Display Label</label>
            <input className={S.input} value={form.label} onChange={e => setForm(f => ({ ...f, label: e.target.value }))} placeholder="e.g. 50T (optional)" />
          </div>
        </div>
        {err && <div className="text-xs text-red-400 mt-2">{err}</div>}
        <button onClick={handleAdd} className={`${S.btn} ${S.btnPrimary} mt-3 text-xs`}>Add Capacity</button>
      </div>
    </div>
  );
}

// ─── COLORS SECTION (read-only info) ──────────────────────────────────────────
function ColorsSection() {
  return (
    <div className={S.section}>
      <div className={S.sectionTitle}>Product Colors</div>
      <div className="flex gap-2">
        {COLORS.map(c => (
          <span key={c} className="text-xs px-3 py-1 rounded font-mono bg-[#0f1117] text-gray-300 border border-[#2a2f3e]">{c}</span>
        ))}
      </div>
      <div className="text-xs text-gray-500 mt-2">
        Colors are fixed: GREY, BLACK, GREEN. Contact dev to add more.
      </div>
    </div>
  );
}

// ─── DATA MANAGEMENT SECTION ───────────────────────────────────────────────────
function DataSection() {
  const { productionData, dispatchData, rawMaterialData } = useData();

  const counts = [
    { label: 'Production entries',   count: productionData.length },
    { label: 'Dispatch entries',     count: dispatchData.length },
    { label: 'Raw material entries', count: rawMaterialData.length },
  ];

  function exportAll() {
    const allData = { productionData, dispatchData, rawMaterialData, exportedAt: new Date().toISOString() };
    const blob = new Blob([JSON.stringify(allData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `production-backup-${new Date().toISOString().slice(0, 10)}.json`; a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className={S.section}>
      <div className={S.sectionTitle}>Data Overview</div>
      <div className="grid grid-cols-2 gap-2 mb-4">
        {counts.map(c => (
          <div key={c.label} className="bg-[#0f1117] rounded p-2 border border-[#2a2f3e]">
            <div className="text-lg font-mono font-bold text-white">{c.count}</div>
            <div className="text-xs text-gray-400">{c.label}</div>
          </div>
        ))}
      </div>
      <button onClick={exportAll} className={`${S.btn} ${S.btnGhost} text-xs w-full`}>
        Export All Data as JSON
      </button>
      <div className="text-xs text-gray-500 mt-2">
        Note: All data is stored in browser memory. Export regularly to avoid data loss on page refresh.
        CSV import is available in each individual tab.
      </div>
    </div>
  );
}

// ─── MAIN PANEL ────────────────────────────────────────────────────────────────
export function SettingsPanel({ onClose }: Props) {
  return (
    <div className={S.overlay} onClick={e => e.target === e.currentTarget && onClose()}>
      <div className={S.panel}>
        <div className={S.header}>
          <span className={S.title}>Settings</span>
          <button onClick={onClose} className="text-gray-400 hover:text-white text-xl leading-none">&times;</button>
        </div>
        <div className={S.body}>
          <ProductTypesSection />
          <ProductSizesSection />
          <CapacitiesSection />
          <ColorsSection />
          <DataSection />
        </div>
      </div>
    </div>
  );
}
