// Generated by build-dashboard skill — auth
import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import { AuthProvider, useAuth } from "./auth/AuthContext";
import { ProtectedRoute } from "./auth/ProtectedRoute";
import { LoginPage } from "./auth/LoginPage";
import { DEFAULT_ROUTE } from "./auth/roleGuard";
import ProductionDashboard from "./dashboards/production/ProductionDashboard";

// DEV BYPASS: set to true to skip auth and go straight to production dashboard
const DEV_PREVIEW = import.meta.env.VITE_DEV_PREVIEW === 'true';

// Placeholder dashboard components — replace as each module is built
const PlaceholderDashboard = ({ name }: { name: string }) => (
  <div className="p-8 text-gray-600">
    <h2 className="text-xl font-semibold">{name} Dashboard</h2>
    <p className="text-sm mt-1 text-gray-400">Coming soon — run /build-dashboard {name.toLowerCase()} to scaffold this module.</p>
  </div>
);

function RootRedirect() {
  const { user } = useAuth();
  if (!user) return <Navigate to="/login" replace />;
  return <Navigate to={DEFAULT_ROUTE[user.role]} replace />;
}

export default function App() {
  if (DEV_PREVIEW) {
    return (
      <BrowserRouter>
        <Routes>
          <Route path="*" element={<ProductionDashboard />} />
        </Routes>
      </BrowserRouter>
    );
  }

  return (
    <AuthProvider>
      <BrowserRouter>
        <Routes>
          <Route path="/login" element={<LoginPage />} />
          <Route path="/" element={<RootRedirect />} />

          <Route path="/executive" element={
            <ProtectedRoute allowedRoles={["executive"]}>
              <PlaceholderDashboard name="Executive" />
            </ProtectedRoute>
          } />

          <Route path="/sales" element={
            <ProtectedRoute allowedRoles={["executive", "sales"]}>
              <PlaceholderDashboard name="Sales" />
            </ProtectedRoute>
          } />

          <Route path="/accounts" element={
            <ProtectedRoute allowedRoles={["executive", "accounts"]}>
              <PlaceholderDashboard name="Accounts" />
            </ProtectedRoute>
          } />

          <Route path="/production" element={
            <ProtectedRoute allowedRoles={["executive", "production"]}>
              <ProductionDashboard />
            </ProtectedRoute>
          } />

          <Route path="/dispatch" element={
            <ProtectedRoute allowedRoles={["executive", "dispatch"]}>
              <PlaceholderDashboard name="Dispatch" />
            </ProtectedRoute>
          } />

          <Route path="/operations" element={
            <ProtectedRoute allowedRoles={["executive", "operations"]}>
              <PlaceholderDashboard name="Operations" />
            </ProtectedRoute>
          } />

          <Route path="/quotation" element={
            <ProtectedRoute allowedRoles={["executive", "quotation"]}>
              <PlaceholderDashboard name="Quotation" />
            </ProtectedRoute>
          } />

          {/* Catch-all */}
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </BrowserRouter>
    </AuthProvider>
  );
}
