// Generated by build-dashboard skill — auth
import { createContext, useContext, useEffect, useState, ReactNode } from "react";
// supabase client imported when backend is configured
// import { supabase } from "./supabaseClient";

export type UserRole =
  | "executive"
  | "sales"
  | "accounts"
  | "production"
  | "dispatch"
  | "operations"
  | "quotation";

export interface AuthUser {
  id: string;
  email: string;
  role: UserRole;
  full_name: string;
  department?: string;
  access_token: string;
}

interface AuthContextValue {
  user: AuthUser | null;
  loading: boolean;
  login: (email: string, password: string) => Promise<void>;
  logout: () => Promise<void>;
}

const AuthContext = createContext<AuthContextValue | null>(null);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<AuthUser | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Restore session from localStorage on mount
    const stored = localStorage.getItem("auth_user");
    if (stored) {
      try { setUser(JSON.parse(stored)); } catch { localStorage.removeItem("auth_user"); }
    }
    setLoading(false);
  }, []);

  async function login(email: string, password: string) {
    const res = await fetch(`${import.meta.env.VITE_API_URL}/auth/login`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email, password }),
    });
    if (!res.ok) {
      const err = await res.json();
      throw new Error(err.detail || "Login failed");
    }
    const data = await res.json();
    const authUser: AuthUser = { ...data.user, access_token: data.access_token };
    setUser(authUser);
    localStorage.setItem("auth_user", JSON.stringify(authUser));
    localStorage.setItem("refresh_token", data.refresh_token);
  }

  async function logout() {
    await fetch(`${import.meta.env.VITE_API_URL}/auth/logout`, {
      method: "POST",
      headers: { Authorization: `Bearer ${user?.access_token}` },
    });
    setUser(null);
    localStorage.removeItem("auth_user");
    localStorage.removeItem("refresh_token");
  }

  return (
    <AuthContext.Provider value={{ user, loading, login, logout }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth(): AuthContextValue {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error("useAuth must be used inside <AuthProvider>");
  return ctx;
}
