// Generated by build-dashboard skill — auth
import { Navigate, useLocation } from "react-router-dom";
import { useAuth } from "./AuthContext";
import { canAccess, DEFAULT_ROUTE } from "./roleGuard";
import type { UserRole } from "./AuthContext";

interface Props {
  children: React.ReactNode;
  /** If provided, only these roles can access this route */
  allowedRoles?: UserRole[];
}

export function ProtectedRoute({ children, allowedRoles }: Props) {
  const { user, loading } = useAuth();
  const location = useLocation();

  if (loading) {
    return <div className="flex items-center justify-center h-screen text-gray-500">Loading...</div>;
  }

  // Not logged in → go to login
  if (!user) {
    return <Navigate to="/login" state={{ from: location }} replace />;
  }

  // Role-based access check
  if (allowedRoles && !allowedRoles.includes(user.role)) {
    // Redirect to their own dashboard instead of a blank 403
    return <Navigate to={DEFAULT_ROUTE[user.role]} replace />;
  }

  // Route-level access check (catches direct URL navigation)
  if (!canAccess(user.role, location.pathname)) {
    return <Navigate to={DEFAULT_ROUTE[user.role]} replace />;
  }

  return <>{children}</>;
}
