// Generated by build-dashboard skill — auth
import { UserRole } from "./AuthContext";

/** Maps each role to the dashboard route it can access */
export const ROLE_ROUTES: Record<UserRole, string[]> = {
  executive:  ["/executive", "/sales", "/accounts", "/production", "/dispatch", "/operations", "/quotation"],
  sales:      ["/sales"],
  accounts:   ["/accounts"],
  production: ["/production"],
  dispatch:   ["/dispatch"],
  operations: ["/operations"],
  quotation:  ["/quotation"],
};

/** Returns the default landing route for a role after login */
export const DEFAULT_ROUTE: Record<UserRole, string> = {
  executive:  "/executive",
  sales:      "/sales",
  accounts:   "/accounts",
  production: "/production",
  dispatch:   "/dispatch",
  operations: "/operations",
  quotation:  "/quotation",
};

/** Display name for each role */
export const ROLE_LABELS: Record<UserRole, string> = {
  executive:  "Executive / CEO",
  sales:      "Sales",
  accounts:   "Accounts & Finance",
  production: "Production",
  dispatch:   "Dispatch",
  operations: "Operations",
  quotation:  "Quotation Tracker",
};

/** Check if a role can access a given route */
export function canAccess(role: UserRole, route: string): boolean {
  return ROLE_ROUTES[role]?.some((r) => route.startsWith(r)) ?? false;
}
